"""Native verifier for godot_components: each component compiles, passes its own GDScript tests, fails them when
gutted, registers its global class, matches its contract card under engine reflection and runs its example scenes.

Every check runs Godot 4 headless (no display, no renderer) in a fresh project inside the item's workspace:

1. godot_parse_check_only: every .gd file of the package passes ``--check-only`` in a project where every GDScript
   warning that Godot enables by default, plus untyped declarations, is raised to an error.
2. godot_gdscript_tests: the shared runner, copied to res://baltor/test_runner/, runs the item's tests from the
   package layout at res://baltor/godot_components/<identity>/; exit code 0, the summary line with failed=0 and
   at least four passes, no SCRIPT ERROR line and nothing leaked at exit. This runs before any editor import, so the
   tests do not depend on the global class cache.
3. godot_tests_reject_gutted_component: a copy of the component whose every function body is replaced by a bare
   return still compiles (default warning levels), and the same tests must then fail.
4. godot_editor_import: ``--import`` builds the global class cache and imports the item's resources without error.
5. godot_contract_reflection: a generated reflection script compares the engine's view of the script (global name,
   base, signals, public methods with argument names and defaults, exported properties with types and default
   values, public properties, class registration) with the contract card.
6. godot_example_scene (when the item has .tscn files): each scene loads, instantiates, runs 20 process and 5
   physics frames, and frees without engine or script errors or orphan nodes.
7. godot_readme_usage_compiles: the first gdscript block of README.md compiles as a script after the import.

No check renders a frame, so the record holds no preview. Durations and absolute paths stay out of the record.
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
import shutil
from pathlib import Path

#: The warnings Godot 4.7 enables by default, raised to errors, plus untyped_declaration (off by default).
STRICT_WARNINGS = (
    "unassigned_variable", "unassigned_variable_op_assign", "unused_variable", "unused_local_constant",
    "unused_private_class_variable", "unused_parameter", "unused_signal", "shadowed_variable",
    "shadowed_variable_base_class", "shadowed_global_identifier", "unreachable_code", "unreachable_pattern",
    "standalone_expression", "standalone_ternary", "incompatible_ternary", "untyped_declaration",
    "unsafe_void_return", "static_called_on_instance", "missing_tool", "redundant_static_unload", "redundant_await",
    "assert_always_true", "assert_always_false", "integer_division", "narrowing_conversion",
    "int_as_enum_without_cast", "int_as_enum_without_match", "enum_variable_without_default", "empty_file",
    "deprecated_keyword", "confusable_identifier", "confusable_local_declaration", "confusable_local_usage",
    "confusable_capture_reassignment", "confusable_temporary_modification", "inference_on_variant",
    "native_method_override", "get_node_default_without_onready", "onready_with_export", "property_used_as_function",
    "constant_used_as_function", "function_used_as_property")
SUMMARY = re.compile(r"^BALTOR_TESTS passed=(\d+) failed=(\d+)\s*$", re.M)
REFLECT = re.compile(r"^BALTOR_REFLECT (\{.*\})\s*$", re.M)
SCRIPT_ERRORS = ("SCRIPT ERROR", "Parse Error")
EXIT_LEAKS = ("leaked at exit", "still in use at exit")
MINIMUM_TESTS = 4
TIMEOUT = 120
RUNNER_FILES = ("run_tests.gd", "baltor_test.gd")
BUILTIN_TYPES = {
    "bool", "int", "float", "String", "StringName", "NodePath", "Vector2", "Vector2i", "Vector3", "Vector3i",
    "Vector4", "Vector4i", "Rect2", "Rect2i", "Transform2D", "Transform3D", "Basis", "Quaternion", "Color", "AABB",
    "Plane", "Projection", "Callable", "Signal", "RID", "Dictionary", "Array", "PackedByteArray", "PackedInt32Array",
    "PackedInt64Array", "PackedFloat32Array", "PackedFloat64Array", "PackedStringArray", "PackedVector2Array",
    "PackedVector3Array", "PackedColorArray", "PackedVector4Array"}
ZERO_RETURNS = {"void": "pass", "bool": "return false", "int": "return 0", "float": "return 0.0",
                "String": 'return ""', "StringName": 'return &""', "NodePath": "return NodePath()",
                "Variant": "return null"}
#: Export types whose contract default is the text value itself; any other type's default text is an expression.
TEXT_EXPORT_TYPES = ("String", "StringName")
#: The variable naming the user runtime folder, where systemd-run --user finds the user bus.
RUNTIME_DIRECTORY_VARIABLE = "XDG_RUNTIME_DIR"

REFLECT_SCRIPT = '''extends SceneTree
## Generated by the godot_components verifier: reflects one component script and runs its example scenes.


class _Catcher extends Logger:
	var entries: Array[String] = []
	var lock: Mutex = Mutex.new()

	func _log_error(_function: String, file: String, line: int, code: String, rationale: String,
			_editor_notify: bool, error_type: int, _script_backtraces: Array[ScriptBacktrace]) -> void:
		if error_type == 1:
			return
		lock.lock()
		entries.append("%s %s (%s:%d)" % [code, rationale, file, line])
		lock.unlock()

	func _log_message(_message: String, _error: bool) -> void:
		pass

	func count() -> int:
		lock.lock()
		var size: int = entries.size()
		lock.unlock()
		return size

	func since(start: int) -> Array:
		lock.lock()
		var copy: Array = entries.slice(start)
		lock.unlock()
		return copy


var _catcher: _Catcher = _Catcher.new()


func _initialize() -> void:
	OS.add_logger(_catcher)
	_main()


func _main() -> void:
	await process_frame
	var arguments: PackedStringArray = OS.get_cmdline_user_args()
	var contract: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(arguments[1]))
	var report: Dictionary = {}
	var start: int = _catcher.count()
	var script := load(arguments[0]) as GDScript
	var loaded: bool = script != null and script.can_instantiate()
	report["loaded"] = loaded
	if loaded:
		_reflect(script, contract, report)
	report["registered"] = _registered(String(contract.get("class_name", "")))
	report["errors"] = _catcher.since(start)
	var scenes: Array = []
	for index in range(2, arguments.size()):
		scenes.append(await _run_scene(arguments[index]))
	report["scenes"] = scenes
	OS.remove_logger(_catcher)
	print("BALTOR_REFLECT " + JSON.stringify(report))
	quit(0)


func _reflect(script: GDScript, contract: Dictionary, report: Dictionary) -> void:
	report["global_name"] = String(script.get_global_name())
	report["base_type"] = String(script.get_instance_base_type())
	var signals: Array = []
	for entry: Dictionary in script.get_script_signal_list():
		signals.append({"name": String(entry["name"]), "args": _names(entry["args"])})
	report["signals"] = signals
	var methods: Array = []
	var seen: Dictionary = {}
	for entry: Dictionary in script.get_script_method_list():
		var method_name: String = entry["name"]
		if method_name.begins_with("_") or method_name.begins_with("@") or seen.has(method_name):
			continue
		seen[method_name] = true
		var returned: Dictionary = entry["return"]
		methods.append({"name": method_name, "args": _names(entry["args"]),
				"defaults": (entry["default_args"] as Array).size(),
				"static": (int(entry["flags"]) & METHOD_FLAG_STATIC) != 0,
				"return_type": type_string(int(returned["type"])),
				"return_variant": (int(returned["usage"]) & PROPERTY_USAGE_NIL_IS_VARIANT) != 0})
	report["methods"] = methods
	var expected: Dictionary = {}
	for row: Dictionary in contract.get("exports_check", []):
		expected[row["name"]] = row
	var instance: Object = script.new()
	var exports: Array = []
	var properties: Array = []
	for entry: Dictionary in script.get_script_property_list():
		var usage: int = entry["usage"]
		if (usage & PROPERTY_USAGE_SCRIPT_VARIABLE) == 0:
			continue
		var property_name: String = entry["name"]
		if (usage & PROPERTY_USAGE_EDITOR) == 0:
			if not property_name.begins_with("_"):
				properties.append(property_name)
			continue
		var value: Variant = instance.get(property_name)
		exports.append({"name": property_name, "type": type_string(int(entry["type"])),
				"class_name": String(entry["class_name"]), "hint_string": String(entry["hint_string"]),
				"value_text": str(value) if typeof(value) == TYPE_OBJECT else var_to_str(value),
				"matches_default": _matches(value, expected.get(property_name, {}), instance)})
	report["exports"] = exports
	report["properties"] = properties
	if instance is Node:
		(instance as Node).free()
	elif not (instance is RefCounted):
		instance.free()


func _names(arguments: Array) -> Array:
	var names: Array = []
	for argument: Dictionary in arguments:
		names.append(String(argument["name"]))
	return names


func _matches(value: Variant, row: Dictionary, instance: Object) -> Variant:
	var kind: String = row.get("kind", "none")
	if kind == "literal":
		return _same(value, row["value"])
	if kind == "expression":
		var expression := Expression.new()
		if expression.parse(String(row["value"])) != OK:
			return null
		var result: Variant = expression.execute([], instance, false)
		if expression.has_execute_failed():
			return null
		return _same(value, result)
	return null


func _same(a: Variant, b: Variant) -> bool:
	var type_a: int = typeof(a)
	var type_b: int = typeof(b)
	var numbers: Array[int] = [TYPE_INT, TYPE_FLOAT]
	var texts: Array[int] = [TYPE_STRING, TYPE_STRING_NAME, TYPE_NODE_PATH]
	if type_a in numbers and type_b in numbers:
		return is_equal_approx(float(a), float(b))
	if type_a in texts and type_b in texts:
		return str(a) == str(b)
	if type_a != type_b:
		return false
	if type_a in [TYPE_VECTOR2, TYPE_VECTOR3, TYPE_VECTOR4, TYPE_COLOR, TYPE_RECT2, TYPE_TRANSFORM2D,
			TYPE_TRANSFORM3D, TYPE_BASIS, TYPE_QUATERNION, TYPE_PLANE, TYPE_AABB]:
		return a.is_equal_approx(b)
	return a == b


func _registered(wanted: String) -> Variant:
	for entry: Dictionary in ProjectSettings.get_global_class_list():
		if String(entry["class"]) == wanted:
			return {"class": String(entry["class"]), "base": String(entry["base"]), "path": String(entry["path"])}
	return null


func _count_nodes(node: Node) -> int:
	var total: int = 1
	for child: Node in node.get_children():
		total += _count_nodes(child)
	return total


func _run_scene(path: String) -> Dictionary:
	var start: int = _catcher.count()
	var orphans: int = int(Performance.get_monitor(Performance.OBJECT_ORPHAN_NODE_COUNT))
	var packed := load(path) as PackedScene
	var outcome: Dictionary = {"path": path, "loaded": packed != null and packed.can_instantiate(), "nodes": 0}
	if outcome["loaded"]:
		var scene_root: Node = packed.instantiate()
		root.add_child(scene_root)
		outcome["nodes"] = _count_nodes(scene_root)
		for _frame in range(20):
			await process_frame
		for _frame in range(5):
			await physics_frame
		scene_root.queue_free()
		await process_frame
		await process_frame
	outcome["errors"] = _catcher.since(start)
	outcome["orphans"] = int(Performance.get_monitor(Performance.OBJECT_ORPHAN_NODE_COUNT)) - orphans
	return outcome
'''


def _inspector(shared_dir: Path):
    specification = importlib.util.spec_from_file_location("godot_components_inspect_gdscript",
                                                           Path(shared_dir) / "inspect_gdscript.py")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def _write_project(project: Path, strict: bool) -> None:
    project.mkdir(parents=True, exist_ok=True)
    lines = ["config_version=5", "", "[application]", "", 'config/name="baltor_component_check"', ""]
    if strict:
        lines += ["[debug]", ""] + [f"gdscript/warnings/{name}=2" for name in STRICT_WARNINGS] + [""]
    (project / "project.godot").write_text("\n".join(lines), encoding="utf-8")


def _install(project: Path, context, source_override: "dict | None" = None) -> Path:
    """Copy the package layout (item files and shared files) and the runner into the project."""
    identity = context.item["identity"]
    package = project / "baltor" / "godot_components" / identity
    for row in context.item["files"]:
        target = package / row["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        if source_override and row["path"] in source_override:
            target.write_text(source_override[row["path"]], encoding="utf-8")
        else:
            shutil.copyfile(Path(context.item_dir) / row["path"], target)
    for row in context.family["shared_files"]:
        shutil.copyfile(Path(context.shared_dir) / row["path"], package / row["path"])
    runner = project / "baltor" / "test_runner"
    runner.mkdir(parents=True, exist_ok=True)
    for name in RUNNER_FILES:
        shutil.copyfile(Path(context.shared_dir) / name, runner / name)
    return package


def _output(outcome: dict) -> str:
    return (outcome.get("stdout") or "") + "\n" + (outcome.get("stderr") or "")


def _tail(text: str, size: int = 1500) -> str:
    lines = [line for line in text.splitlines() if line.strip() and not line.startswith("Godot Engine v")]
    return "\n".join(lines)[-size:]


def _check(name: str, passed: bool, detail: dict) -> dict:
    return {"name": name, "state": "passed" if passed else "failed", "detail": detail}


def _errors_in(text: str) -> list:
    return [line.strip() for line in text.splitlines() if any(marker in line for marker in SCRIPT_ERRORS)][:8]


def _run_tests(run, project: Path, identity: str) -> dict:
    outcome = run(project, ["--script", "res://baltor/test_runner/run_tests.gd", "--",
                            f"res://baltor/godot_components/{identity}/tests"])
    text = _output(outcome)
    found = SUMMARY.findall(text)
    passed, failed = (int(found[-1][0]), int(found[-1][1])) if found else (0, 0)
    names = sorted(line.split("::", 1)[1] for line in text.splitlines() if line.startswith("ok ") and "::" in line)
    failures = [line[5:].split("::", 1)[-1][:300] for line in text.splitlines() if line.startswith("FAIL ")]
    return {"outcome": outcome, "text": text, "summary": bool(found), "passed": passed, "failed": failed,
            "names": names, "failures": failures}


def gutted_source(source: str, inspector) -> tuple:
    """(source with every function body replaced by a bare return of its declared type, functions replaced)."""
    rows = inspector.logical_lines(source)
    enums = set()
    for row in rows:
        found = re.match(r"enum\s+([A-Za-z_][A-Za-z0-9_]*)", row["code"])
        if found:
            enums.add(found.group(1))
    replacements = []
    for index, row in enumerate(rows):
        code = row["code"]
        while code.startswith("@"):
            code = inspector._take_annotation(code)[1]
        declaration = code[len("static "):].lstrip() if code.startswith("static ") else code
        if not declaration.startswith("func "):
            continue
        parsed = inspector.parse_source(declaration)
        if not parsed["methods"]:
            continue
        returns = parsed["methods"][0]["returns"]
        body = []
        for later in rows[index + 1:]:
            if len(later["indent"]) <= len(row["indent"]):
                break
            body.append(later)
        if not body:
            continue
        if returns is None:
            statement = "return null"
        elif returns in ZERO_RETURNS:
            statement = ZERO_RETURNS[returns]
        elif returns.startswith("Array["):
            statement = "return []"
        elif returns.startswith("Dictionary["):
            statement = "return {}"
        elif returns in BUILTIN_TYPES:
            statement = f"return {returns}()"
        elif returns.split(".")[-1] in enums:
            statement = "return 0"
        else:
            statement = "return null"
        replacements.append((body[0]["line"], body[-1]["end_line"], row["indent"] + "\t" + statement))
    lines = source.split("\n")
    for first, last, text in sorted(replacements, reverse=True):
        lines[first - 1:last] = [text]
    return "\n".join(lines), len(replacements)


def _usage_snippet(readme: str) -> "str | None":
    found = re.search(r"```gdscript\n(.*?)```", readme, re.S)
    return found.group(1) if found else None


def _contract_check_rows(contract: dict) -> list:
    rows = []
    for row in contract.get("exports", []):
        default, kind = row.get("default"), "none"
        if isinstance(default, bool) or isinstance(default, (int, float)):
            kind = "literal"
        elif isinstance(default, str):
            quoted = re.fullmatch(r'[&^]"((?:[^"\\]|\\.)*)"', default)
            if quoted:
                kind, default = "literal", re.sub(r"\\(.)", r"\1", quoted.group(1))
            else:
                kind = "literal" if row.get("type") in TEXT_EXPORT_TYPES else "expression"
        rows.append({"name": row["name"], "kind": kind, "value": default})
    return rows


def _argument_name(argument: str) -> str:
    return re.split(r"[:=\s]", argument.strip(), maxsplit=1)[0]


def compare_reflection(contract: dict, report: dict, identity: str) -> tuple:
    """(problems, counts): differences between the contract card and the engine's reflection of the script."""
    problems, counts = [], {"signals": 0, "methods": 0, "exports": 0, "defaults_checked": 0, "properties": 0}
    if not report.get("loaded"):
        return ["the component script did not load in the engine"], counts
    if report.get("errors"):
        problems.append(f"errors while reflecting: {report['errors'][:3]}")
    if report.get("global_name") != contract["class_name"]:
        problems.append(f"global name {report.get('global_name')!r} is not {contract['class_name']!r}")
    extends = contract.get("extends") or ""
    native_base = re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", extends) is not None
    if native_base and report.get("base_type") != extends:
        problems.append(f"instance base {report.get('base_type')!r} is not {extends!r}")
    engine_signals = {row["name"]: row["args"] for row in report.get("signals", [])}
    card_signals = {row["name"]: [_argument_name(a) for a in row["arguments"]] for row in contract.get("signals", [])}
    if engine_signals != card_signals:
        problems.append(f"signals differ: engine {engine_signals}, card {card_signals}")
    counts["signals"] = len(card_signals)
    engine_methods = {row["name"]: row for row in report.get("methods", [])}
    card_methods = {row["name"]: row for row in contract.get("methods", [])}
    if set(engine_methods) != set(card_methods):
        problems.append(f"public methods differ: engine {sorted(engine_methods)}, card {sorted(card_methods)}")
    for name in sorted(set(engine_methods) & set(card_methods)):
        engine, card = engine_methods[name], card_methods[name]
        arguments = [_argument_name(a) for a in card["arguments"]]
        defaults = sum(1 for a in card["arguments"] if "=" in a)
        if engine["args"] != arguments or engine["defaults"] != defaults:
            problems.append(f"{name}: engine arguments {engine['args']} with {engine['defaults']} defaults, "
                            f"card {arguments} with {defaults}")
        if engine["static"] != bool(card.get("static", False)):
            problems.append(f"{name}: static is {engine['static']} in the engine")
        returns = card.get("returns")
        if returns == "void" and (engine["return_type"] != "Nil" or engine["return_variant"]):
            problems.append(f"{name}: the engine does not see a void return")
        elif returns in BUILTIN_TYPES and engine["return_type"] != returns:
            problems.append(f"{name}: engine return type {engine['return_type']}, card {returns}")
        elif (returns or "").startswith(("Array[", "Dictionary[")) and engine["return_type"] != returns.split("[")[0]:
            problems.append(f"{name}: engine return type {engine['return_type']}, card {returns}")
    counts["methods"] = len(card_methods)
    engine_exports = {row["name"]: row for row in report.get("exports", [])}
    card_exports = {row["name"]: row for row in contract.get("exports", [])}
    if set(engine_exports) != set(card_exports):
        problems.append(f"exports differ: engine {sorted(engine_exports)}, card {sorted(card_exports)}")
    for name in sorted(set(engine_exports) & set(card_exports)):
        engine, card = engine_exports[name], card_exports[name]
        kind = (card.get("type") or "").split("[")[0]
        if kind in BUILTIN_TYPES and engine["type"] != kind:
            problems.append(f"{name}: engine type {engine['type']}, card {card.get('type')}")
        elif kind and kind not in BUILTIN_TYPES and engine["type"] == "Object" \
                and kind not in (engine["class_name"], engine["hint_string"]):
            problems.append(f"{name}: engine class {engine['class_name'] or engine['hint_string']}, card {kind}")
        if engine["matches_default"] is False:
            problems.append(f"{name}: engine default {engine['value_text']}, card {card.get('default')!r}")
        elif engine["matches_default"] is True:
            counts["defaults_checked"] += 1
    counts["exports"] = len(card_exports)
    card_properties = {row["name"] for row in contract.get("properties", []) if not row.get("static")}
    engine_properties = set(report.get("properties", []))
    if engine_properties != card_properties:
        problems.append(f"properties differ: engine {sorted(engine_properties)}, card {sorted(card_properties)}")
    counts["properties"] = len(card_properties)
    registered = report.get("registered")
    expected_path = f"res://baltor/godot_components/{identity}/{identity}.gd"
    if not registered or registered.get("path") != expected_path:
        problems.append(f"the global class cache does not register {contract['class_name']} at {expected_path}")
    elif native_base and registered.get("base") != extends:
        problems.append(f"the global class cache gives base {registered.get('base')!r}")
    return problems, counts


def verify(context) -> dict:
    engines = context.engines
    engine = engines.locate("godot")
    item, identity = context.item, context.item["identity"]
    workspace = Path(context.workspace)
    inspector = _inspector(context.shared_dir)
    contract = item["contract"]

    # engines.run gives the engine an XDG_RUNTIME_DIR inside the workspace, where systemd-run --user finds no bus,
    # so its memory-capped scope fails before Godot starts. The real runtime directory keeps the scope working.
    runtime = {RUNTIME_DIRECTORY_VARIABLE: os.environ.get(RUNTIME_DIRECTORY_VARIABLE) or f"/run/user/{os.getuid()}"}

    def run(project: Path, arguments: list, timeout: int = TIMEOUT) -> dict:
        return engines.run(engine, ["--headless", "--path", str(project), *arguments], workspace=workspace,
                           timeout=timeout, environment=runtime)

    project = workspace / "project"
    _write_project(project, strict=True)
    package = _install(project, context)
    base = f"res://baltor/godot_components/{identity}"
    checks = []

    scripts = sorted([row["path"] for row in item["files"] if row["path"].endswith(".gd")] + list(RUNNER_FILES))
    parse_failures = []
    for path in scripts:
        outcome = run(project, ["--check-only", "--script", f"{base}/{path}"])
        text = _output(outcome)
        if outcome["returncode"] != 0 or _errors_in(text):
            parse_failures.append({"file": path, "returncode": outcome["returncode"], "errors": _errors_in(text),
                                   "output_tail": _tail(text, 600)})
    checks.append(_check("godot_parse_check_only", not parse_failures,
                         {"files": scripts, "strict_warnings": len(STRICT_WARNINGS), "failures": parse_failures}))

    tests = _run_tests(run, project, identity)
    leaks = [line.strip() for line in tests["text"].splitlines() if any(marker in line for marker in EXIT_LEAKS)]
    tests_ok = (tests["outcome"]["returncode"] == 0 and tests["summary"] and tests["failed"] == 0
                and tests["passed"] >= MINIMUM_TESTS and not _errors_in(tests["text"]) and not leaks)
    detail = {"runner": "res://baltor/test_runner/run_tests.gd", "tests_folder": f"{base}/tests",
              "passed": tests["passed"], "failed": tests["failed"], "tests": tests["names"]}
    if not tests_ok:
        detail.update({"returncode": tests["outcome"]["returncode"], "timed_out": tests["outcome"]["timed_out"],
                       "summary_line": tests["summary"], "failures": tests["failures"][:10], "leaks": leaks,
                       "script_errors": _errors_in(tests["text"]), "output_tail": _tail(tests["text"])})
    checks.append(_check("godot_gdscript_tests", tests_ok, detail))

    script_name = f"{identity}.gd"
    mutant_text, gutted = gutted_source((Path(context.item_dir) / script_name).read_text(encoding="utf-8"), inspector)
    mutant = workspace / "mutant"
    _write_project(mutant, strict=False)
    _install(mutant, context, {script_name: mutant_text})
    compiled = run(mutant, ["--check-only", "--script", f"{base}/{script_name}"])
    mutant_tests = _run_tests(run, mutant, identity)
    mutant_ok = (gutted > 0 and compiled["returncode"] == 0 and not _errors_in(_output(compiled))
                 and mutant_tests["summary"] and mutant_tests["failed"] > 0
                 and mutant_tests["outcome"]["returncode"] not in (0, None)
                 and "did not load or compile" not in mutant_tests["text"])
    detail = {"gutted_functions": gutted, "mutant_compiles": compiled["returncode"] == 0,
              "passed": mutant_tests["passed"], "failed": mutant_tests["failed"]}
    if not mutant_ok:
        detail.update({"compile_errors": _errors_in(_output(compiled)), "output_tail": _tail(mutant_tests["text"])})
    checks.append(_check("godot_tests_reject_gutted_component", mutant_ok, detail))
    shutil.rmtree(mutant, ignore_errors=True)

    imported = run(project, ["--import"], timeout=240)
    import_text = _output(imported)
    import_ok = imported["returncode"] == 0 and not _errors_in(import_text)
    detail = {"class_cache": (project / ".godot" / "global_script_class_cache.cfg").is_file()}
    import_ok = import_ok and detail["class_cache"]
    if not import_ok:
        detail.update({"returncode": imported["returncode"], "errors": _errors_in(import_text),
                       "output_tail": _tail(import_text)})
    checks.append(_check("godot_editor_import", import_ok, detail))

    verifier = project / "baltor_verify"
    verifier.mkdir(parents=True, exist_ok=True)
    (verifier / "reflect.gd").write_text(REFLECT_SCRIPT, encoding="utf-8")
    (verifier / "contract.json").write_text(json.dumps({"class_name": contract["class_name"],
                                                        "exports_check": _contract_check_rows(contract)}),
                                            encoding="utf-8")
    scenes = sorted(row["path"] for row in item["files"] if row["path"].endswith(".tscn"))
    reflected = run(project, ["--script", "res://baltor_verify/reflect.gd", "--", f"{base}/{script_name}",
                              "res://baltor_verify/contract.json", *[f"{base}/{path}" for path in scenes]])
    reflect_text = _output(reflected)
    found = REFLECT.findall(reflect_text)
    report = json.loads(found[-1]) if found else {}
    problems, counts = compare_reflection(contract, report, identity) if report else (
        ["the reflection script printed no report"], {})
    detail = dict(counts)
    if problems:
        detail.update({"problems": problems[:12], "output_tail": _tail(reflect_text, 800)})
    checks.append(_check("godot_contract_reflection", not problems, detail))
    if scenes:
        rows, scene_ok = [], bool(report)
        for row in report.get("scenes", []):
            good = row.get("loaded") and not row.get("errors") and row.get("orphans", 0) <= 0
            scene_ok = scene_ok and bool(good)
            rows.append({"path": row["path"].rsplit("/", 1)[-1], "loaded": row.get("loaded"),
                         "nodes": row.get("nodes"), "errors": row.get("errors", [])[:3],
                         "orphans": row.get("orphans")})
        scene_ok = scene_ok and len(rows) == len(scenes)
        checks.append(_check("godot_example_scene", scene_ok, {"scenes": rows, "process_frames": 20,
                                                                "physics_frames": 5}))

    snippet = _usage_snippet((Path(context.item_dir) / "README.md").read_text(encoding="utf-8"))
    usage_ok, detail = False, {"snippet_found": snippet is not None}
    if snippet is not None:
        (verifier / "usage_example.gd").write_text(snippet, encoding="utf-8")
        compiled = run(project, ["--check-only", "--script", "res://baltor_verify/usage_example.gd"])
        usage_ok = compiled["returncode"] == 0 and not _errors_in(_output(compiled))
        detail["lines"] = len(snippet.strip().splitlines())
        if not usage_ok:
            detail.update({"errors": _errors_in(_output(compiled)), "output_tail": _tail(_output(compiled), 600)})
    checks.append(_check("godot_readme_usage_compiles", usage_ok, detail))
    return {"engine": engine.identity() | {"renderer": "headless"}, "checks": checks, "preview": None}
