"""Geometric algebra Cl(4,0): multivectors, wedge and geometric products, rotors and bivector decomposition.

A multivector is a list of 16 coefficients indexed by blade bitmask (bit 0 = e1 = x, bit 1 = e2 = y, bit 2 = e3 = z,
bit 3 = e4 = w). The product of two basis blades has mask a XOR b and the sign of the swaps that sort the factors
(every e_i squares to +1). A bivector B generates the rotor R = exp(-B/2) and the rotation v -> R v R~; B = t e12
turns x toward y by t. Every 4D bivector is B = B1 + B2 with commuting simple parts in orthogonal planes. With
B^2 = S + q I (scalar S, pseudoscalar I = e1234), lambda = alpha^2, beta^2 are the roots of t^2 + S t + (q/2)^2 and
    B1 = B (alpha^2 + (q/2) I)/(alpha^2 - beta^2),   B2 = B (beta^2 + (q/2) I)/(beta^2 - alpha^2),
so exp(B) = (cos alpha + b1 sin alpha)(cos beta + b2 sin beta). B is simple exactly when B ^ B = 0. Rates p and q in
two orthogonal planes move the point (1, 0, 1, 0)/sqrt(2) along a (p, q) torus knot on the Clifford torus; the CLI
writes its stereographic image (a trefoil for 2 and 3) with the torus as a translucent shell.

    python rotor_bivector_algebra.py --p 2 --q 3 --out trefoil.gltf
"""
from __future__ import annotations

import argparse
import json
import math
import sys

import fourd

PLANE_MASKS = {"xy": 0b0011, "xz": 0b0101, "xw": 0b1001, "yz": 0b0110, "yw": 0b1010, "zw": 0b1100}
PSEUDOSCALAR = 0b1111


def _sign(a, b):
    a >>= 1
    swaps = 0
    while a:
        swaps += bin(a & b).count("1")
        a >>= 1
    return -1.0 if swaps & 1 else 1.0


def blade(mask, value=1.0):
    """A multivector holding one basis blade."""
    if not 0 <= mask < 16:
        raise ValueError("blade masks run from 0 to 15")
    result = [0.0] * 16
    result[mask] = float(value)
    return result


def vector(point):
    """The grade-1 multivector x e1 + y e2 + z e3 + w e4."""
    result = [0.0] * 16
    for axis, value in enumerate(point):
        result[1 << axis] = float(value)
    return result


def bivector(planes):
    """A bivector from plane coefficients ("xy=0.3,zw=1.1" or {"xy": 0.3}); xy means e1^e2."""
    pairs = fourd.parse_rotation(planes) if isinstance(planes, str) else list(dict(planes).items())
    result = [0.0] * 16
    for plane, value in pairs:
        if plane not in PLANE_MASKS:
            first, second = plane[1], plane[0]
            plane, value = first + second, -value
        result[PLANE_MASKS[plane]] += float(value)
    return result


def product(a, b):
    """The geometric product."""
    result = [0.0] * 16
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                if y:
                    result[i ^ j] += _sign(i, j) * x * y
    return result


def wedge(a, b):
    """The outer product (blades sharing no basis vector)."""
    result = [0.0] * 16
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                if y and not i & j:
                    result[i | j] += _sign(i, j) * x * y
    return result


def grade(a, k):
    """The grade-k part."""
    return [value if bin(mask).count("1") == k else 0.0 for mask, value in enumerate(a)]


def reverse(a):
    """The reversion: a blade of grade k changes sign when k(k-1)/2 is odd."""
    return [value * (-1.0 if (bin(mask).count("1") * (bin(mask).count("1") - 1) // 2) & 1 else 1.0)
            for mask, value in enumerate(a)]


def add(a, b, factor=1.0):
    """a + factor b."""
    return [x + factor * y for x, y in zip(a, b)]


def magnitude(a):
    """The Euclidean norm of the coefficients."""
    return math.sqrt(sum(value * value for value in a))


def exp_multivector(a, terms=14):
    """exp(a) by scaling and squaring a truncated Taylor series."""
    size = magnitude(a)
    squarings = max(0, int(math.ceil(math.log2(size / 0.25)))) if size > 0.25 else 0
    small = [value / (2 ** squarings) for value in a]
    total, term = blade(0), blade(0)
    for n in range(1, terms):
        term = [value / n for value in product(term, small)]
        total = add(total, term)
    for _ in range(squarings):
        total = product(total, total)
    return total


def rotor(planes_or_bivector):
    """The rotor exp(-B/2) of a bivector."""
    b = bivector(planes_or_bivector) if not isinstance(planes_or_bivector, list) else planes_or_bivector
    if magnitude(add(b, grade(b, 2), -1.0)) > 1e-12:
        raise ValueError("a rotor is generated by a pure bivector")
    return exp_multivector([-value / 2.0 for value in b])


def sandwich(r, point):
    """The rotated vector R v R~ as a 4-tuple."""
    result = product(product(r, vector(point)), reverse(r))
    return tuple(result[1 << axis] for axis in range(4))


def rotor_matrix(r):
    """The 4x4 rotation matrix of a rotor (columns are the rotated axes)."""
    columns = [sandwich(r, tuple(1.0 if axis == index else 0.0 for axis in range(4))) for index in range(4)]
    return fourd.transpose(columns)


def is_simple(b, tolerance=1e-12):
    """True when B ^ B = 0 (B lies in one plane)."""
    return magnitude(wedge(b, b)) <= tolerance


def split_bivector(b):
    """(B1, B2): commuting simple bivectors in orthogonal planes, |B1| >= |B2|; refused for isoclinic bivectors."""
    square = product(b, b)
    scalar, quartic = square[0], square[PSEUDOSCALAR]
    disc = math.sqrt(max(0.0, scalar * scalar - quartic * quartic))
    large, small = (-scalar + disc) / 2.0, (-scalar - disc) / 2.0
    if large - small <= 1e-12 * max(1.0, large):
        raise ValueError("isoclinic bivector: the two planes are not unique")
    first = product(b, add(blade(0, large), blade(PSEUDOSCALAR, quartic / 2.0)))
    second = product(b, add(blade(0, small), blade(PSEUDOSCALAR, quartic / 2.0)))
    return ([value / (large - small) for value in first], [value / (small - large) for value in second])


def exp_split(b):
    """exp(B) from the decomposition: (cos a + b1 sin a)(cos b + b2 sin b) with a = |B1|, b = |B2|."""
    first, second = split_bivector(b)
    factors = []
    for part in (first, second):
        angle = magnitude(part)
        unit = [value / angle for value in part] if angle > 0.0 else [0.0] * 16
        factors.append(add(blade(0, math.cos(angle)), unit, math.sin(angle)))
    return product(factors[0], factors[1])


def reflection(point, normal):
    """-n v n / |n|^2: the mirror image of a point in the hyperplane orthogonal to n."""
    n = vector(normal)
    result = product(product(n, vector(point)), n)
    norm2 = fourd.dot(normal, normal)
    return tuple(-result[1 << axis] / norm2 for axis in range(4))


def torus_knot(p=2, q=3, samples=180):
    """The orbit of (1, 0, 1, 0)/sqrt(2) under exp(-t B/2) with B = p e12 + q e34, t in [0, 2 pi), in 4D."""
    b = bivector({"xy": float(p), "zw": float(q)})
    start = (2 ** -0.5, 0.0, 2 ** -0.5, 0.0)
    return [sandwich(rotor([value * 2.0 * math.pi * k / samples for value in b]), start) for k in range(samples)]


def linking_number(curve_a, curve_b):
    """Gauss linking integral of two closed polygons (rounded later by the caller)."""
    total = 0.0
    segments_a = list(zip(curve_a, curve_a[1:] + curve_a[:1]))
    segments_b = list(zip(curve_b, curve_b[1:] + curve_b[:1]))
    for a0, a1 in segments_a:
        da = fourd.sub(a1, a0)
        ma = fourd.lerp(a0, a1, 0.5)
        for b0, b1 in segments_b:
            db = fourd.sub(b1, b0)
            r = fourd.sub(ma, fourd.lerp(b0, b1, 0.5))
            distance = fourd.norm(r)
            total += fourd.dot(r, fourd.cross3(da, db)) / distance ** 3
    return total / (4.0 * math.pi)


def winding_about_z(curve):
    """Turns of a closed 3D curve around the z axis."""
    total = 0.0
    for a, b in zip(curve, curve[1:] + curve[:1]):
        step = math.atan2(b[1], b[0]) - math.atan2(a[1], a[0])
        total += (step + math.pi) % (2.0 * math.pi) - math.pi
    return total / (2.0 * math.pi)


def meshes(p=2, q=3, samples=180, radius=0.06, shell=True, sides=6):
    """The stereographic image of the knot as a tube and, optionally, of the Clifford torus as a translucent shell."""
    knot = [fourd.stereographic(point, 1.0) for point in torus_knot(p, q, samples)]
    colours = [fourd.depth_color(k / samples) for k in range(samples)]
    parts = [dict(fourd.tube_mesh(knot, [(k, (k + 1) % samples) for k in range(samples)], radius, sides, colours),
                  name="torus_knot")]
    if shell:
        rows, columns = 18, 40
        points, normals, indices = [], [], []
        for i in range(rows):
            for j in range(columns):
                u, v = 2 * math.pi * j / columns, 2 * math.pi * i / rows
                point4 = (math.cos(u) * 2 ** -0.5, math.sin(u) * 2 ** -0.5, math.cos(v) * 2 ** -0.5, math.sin(v) * 2 ** -0.5)
                points.append(fourd.stereographic(point4, 1.0))
        for i in range(rows):
            for j in range(columns):
                a, b = i * columns + j, i * columns + (j + 1) % columns
                c, d = ((i + 1) % rows) * columns + (j + 1) % columns, ((i + 1) % rows) * columns + j
                indices += [a, b, c, a, c, d]
        accumulated = [[0.0, 0.0, 0.0] for _ in points]
        for start in range(0, len(indices), 3):
            x, y, z = indices[start:start + 3]
            normal = fourd.cross3(fourd.sub(points[y], points[x]), fourd.sub(points[z], points[x]))
            for vertex in (x, y, z):
                for axis in range(3):
                    accumulated[vertex][axis] += normal[axis]
        normals = [fourd.normalize(n) for n in accumulated]
        parts.append({"positions": points, "normals": normals, "indices": indices, "colors": None, "mode": 4,
                      "name": "clifford_torus", "color": (0.55, 0.62, 0.8, 0.22)})
    return parts


def export(path, p=2, q=3, samples=180, radius=0.06, shell=True, sides=6):
    document = fourd.gltf_document(meshes(p, q, samples, radius, shell, sides), generator="rotor_bivector_algebra.py")
    return {"path": str(path), "bytes": fourd.write_gltf(path, document), **fourd.gltf_summary(document)}


def rotations():
    """Matrices of rotors (checked by the package tests)."""
    return [rotor_matrix(rotor("xy=0.3,zw=1.1")), rotor_matrix(rotor("xw=0.4,yz=-0.8,xz=0.2"))]


def invariants():
    turn = rotor("xy=0.9")
    plain = fourd.plane_rotation("xy", 0.9)
    matrix_error = max(abs(a - b) for row_a, row_b in zip(rotor_matrix(turn), plain) for a, b in zip(row_a, row_b))
    general = bivector("xy=0.4,xz=-0.7,xw=0.25,yz=0.6,yw=0.1,zw=-0.9")
    first, second = split_bivector(general)
    series = exp_multivector(general)
    closed = exp_split(general)
    knot = [fourd.stereographic(point, 1.0) for point in torus_knot(2, 3, 160)]
    circle = [(math.cos(2 * math.pi * k / 80), math.sin(2 * math.pi * k / 80), 0.0) for k in range(80)]
    on_torus = all(abs(math.hypot(point[0], point[1]) - 2 ** -0.5) < 1e-12 and abs(math.hypot(point[2], point[3]) - 2 ** -0.5) < 1e-12
                   for point in torus_knot(2, 3, 60))
    r = rotor("xw=0.4,yz=-0.8,xz=0.2")
    unit = product(r, reverse(r))
    return {"e1e2_squares_to_minus_one": product(blade(0b0011), blade(0b0011))[0],
            "pseudoscalar_squares_to_one": product(blade(PSEUDOSCALAR), blade(PSEUDOSCALAR))[0],
            "rotor_matches_plane_rotation": matrix_error < 1e-12,
            "rotor_is_unit": abs(unit[0] - 1.0) < 1e-12 and magnitude(add(unit, blade(0), -1.0)) < 1e-12,
            "split_sums_back": magnitude(add(add(first, second), general, -1.0)) < 1e-12,
            "split_parts_simple": [is_simple(first), is_simple(second)],
            "split_parts_commute": magnitude(add(product(first, second), product(second, first), -1.0)) < 1e-12,
            "general_bivector_simple": is_simple(general), "plane_bivector_simple": is_simple(bivector("xy=1,xz=2")),
            "exp_series_matches_split": magnitude(add(series, closed, -1.0)) < 1e-10,
            "split_magnitudes_xy03_zw11": [round(magnitude(part), 12) for part in split_bivector(bivector("xy=0.3,zw=1.1"))],
            "two_reflections_make_rotation": [round(v, 12) for v in reflection(reflection((1.0, 0.0, 0.0, 0.0), (0, 1, 0, 0)),
                                                                                (1, -1, 0, 0))],
            "knot_on_clifford_torus": on_torus,
            "trefoil_winding_about_z": round(winding_about_z(knot), 9),
            "trefoil_linking_with_unit_circle": round(linking_number(knot, circle))}


def controls():
    def refused(action):
        try:
            action()
        except ValueError:
            return True
        return False

    general = bivector("xy=0.4,xz=-0.7,xw=0.25,yz=0.6,yw=0.1,zw=-0.9")
    first, second = split_bivector(general)
    knot = [fourd.stereographic(point, 1.0) for point in torus_knot(2, 3, 160)]
    far_circle = [(5.0 + math.cos(2 * math.pi * k / 80), math.sin(2 * math.pi * k / 80), 0.0) for k in range(80)]
    return {"isoclinic_split_refused": refused(lambda: split_bivector(bivector("xy=1,zw=1"))),
            "vector_generator_refused": refused(lambda: rotor(vector((1.0, 0.0, 0.0, 0.0)))),
            "unknown_plane_refused": refused(lambda: bivector("xq=1")),
            "general_bivector_not_simple": not is_simple(add(first, second)),
            "unlinked_circle_has_zero_linking": round(linking_number(knot, far_circle)) == 0}


def main(argv=None):
    parser = argparse.ArgumentParser(prog="rotor_bivector_algebra.py",
                                     description="Write the (p, q) torus knot traced by a double rotation.")
    parser.add_argument("--p", type=int, default=2, help="rate in the xy plane (integer, 1 or more)")
    parser.add_argument("--q", type=int, default=3, help="rate in the zw plane (integer, 1 or more)")
    parser.add_argument("--samples", type=int, default=180, help="points along the knot")
    parser.add_argument("--sides", type=int, default=6, help="sides of the knot tube (3 or more)")
    parser.add_argument("--radius", type=float, default=0.06, help="tube radius")
    parser.add_argument("--shell", choices=("on", "off"), default="on", help="include the translucent Clifford torus")
    parser.add_argument("--out", required=True, help="output .gltf")
    args = parser.parse_args(argv)
    if args.p < 1 or args.q < 1 or not 16 <= args.samples <= 4000 or args.radius <= 0 or args.sides < 3:
        parser.error("p and q are 1 or more, samples 16 to 4000, radius positive, sides 3 or more")
    summary = export(args.out, args.p, args.q, args.samples, args.radius, args.shell == "on", args.sides)
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
