"""The 24-cell (Schlafli symbol {3,4,3}) as the 24 Hurwitz unit quaternions.

The vertices are generated, not listed: the closure of the quaternions i and (-1 + i + j + k)/2 under
multiplication is the binary tetrahedral group of order 24. Its elements are the unit Hurwitz integers
(+-1, +-i, +-j, +-k and (+-1 +-i +-j +-k)/2). The cells point toward the 24 directions (+-1, +-1, 0, 0)/sqrt(2),
which form another 24-cell, so the polytope is self-dual. The three cosets of the quaternion group
{+-1, +-i, +-j, +-k} split the vertices into three inscribed 16-cells; the wireframe export colours vertices by
coset, so every edge joins two different colours.

    python icositetrachoron_24cell.py --rotate xw=0.4,yz=0.25 --out 24cell.gltf
"""
from __future__ import annotations

import argparse
import itertools
import json
import sys

import fourd

GENERATORS = ((0.0, 1.0, 0.0, 0.0), (-0.5, 0.5, 0.5, 0.5))


def closure(generators, limit=200):
    """Every product of the unit quaternion generators (the group they generate); non-unit input is refused."""
    for generator in generators:
        if abs(fourd.norm(generator) - 1.0) > 1e-9:
            raise ValueError("generators are unit quaternions")
    found = {fourd.point_key((1.0, 0.0, 0.0, 0.0)): (1.0, 0.0, 0.0, 0.0)}
    frontier = list(found.values())
    while frontier:
        fresh = []
        for element in frontier:
            for generator in generators:
                product = fourd.quat_mul(element, generator)
                key = fourd.point_key(product)
                if key not in found:
                    found[key] = product
                    fresh.append(product)
                    if len(found) > limit:
                        raise ValueError(f"the generated group exceeds {limit} elements")
        frontier = fresh
    return [found[key] for key in sorted(found)]


def hurwitz_units():
    """The 24 unit Hurwitz quaternions, generated by closure."""
    return closure(GENERATORS)


def is_group(elements, tolerance=1e-9):
    """Closed under multiplication and inverses, and holding the identity."""
    keys = {fourd.point_key(element) for element in elements}
    if fourd.point_key((1.0, 0.0, 0.0, 0.0)) not in keys:
        return False
    for a in elements:
        if fourd.point_key(fourd.quat_conjugate(a)) not in keys:
            return False
        for b in elements:
            if fourd.point_key(fourd.quat_mul(a, b)) not in keys:
                return False
    return True


def cosets():
    """The three left cosets g Q8 of the quaternion group Q8 = {+-1, +-i, +-j, +-k} in the Hurwitz units."""
    units = hurwitz_units()
    q8 = [element for element in units if max(abs(value) for value in element) == 1.0]
    groups, seen = [], set()
    for element in units:
        key = fourd.point_key(element)
        if key in seen:
            continue
        coset = sorted((fourd.quat_mul(element, member) for member in q8), key=fourd.point_key)
        seen.update(fourd.point_key(member) for member in coset)
        groups.append(coset)
    return groups


def facet_normals():
    """The 24 cell directions (+-1, +-1, 0, 0)/sqrt(2) in every coordinate pair."""
    normals = []
    for first, second in itertools.combinations(range(4), 2):
        for a, b in itertools.product((-1.0, 1.0), repeat=2):
            vector = [0.0] * 4
            vector[first], vector[second] = a, b
            normals.append(fourd.normalize(vector))
    return normals


def polytope():
    """The 24-cell with unit circumradius and unit edge, vertices at the Hurwitz units read as (x, y, z, w)."""
    points = [fourd.quaternion_to_point(element) for element in hurwitz_units()]
    return fourd.polytope_from_facets(points, facet_normals())


def is_24cell(points, tolerance=1e-9):
    """24 points on one sphere, each with exactly 8 neighbours at a distance equal to the circumradius."""
    if len(points) != 24:
        return False
    middle = fourd.centroid(points)
    radius = fourd.distance(points[0], middle)
    for point in points:
        if abs(fourd.distance(point, middle) - radius) > tolerance:
            return False
        if sum(1 for other in points if abs(fourd.distance(point, other) - radius) <= tolerance) != 8:
            return False
    return True


def is_sixteen_cell(points, tolerance=1e-9):
    """8 points, each with one antipode at 2R and six neighbours at R sqrt(2)."""
    if len(points) != 8:
        return False
    middle = fourd.centroid(points)
    radius = fourd.distance(points[0], middle)
    for point in points:
        distances = sorted(fourd.distance(point, other) for other in points if other is not point)
        if any(abs(value - radius * 2 ** 0.5) > tolerance for value in distances[:6]) or \
                abs(distances[6] - 2.0 * radius) > tolerance:
            return False
    return True


def dual_vertices():
    """Cell centroids pushed out to the circumsphere: the vertices of the dual 24-cell."""
    shape = polytope()
    return [fourd.normalize(fourd.centroid([shape["vertices"][v] for v in members]))
            for members in fourd.cell_vertex_sets(shape)]


def wireframe(rotation="xw=0.4,yz=0.25", projection="perspective", eye=2.6, style="tubes", radius=0.022, sides=8):
    """The rotated 24-cell projected to 3D, vertices coloured by Q8 coset."""
    shape = polytope()
    colour_of = {}
    for index, coset in enumerate(cosets()):
        for element in coset:
            colour_of[fourd.point_key(fourd.quaternion_to_point(element))] = fourd.palette(3)[index]
    colours = [colour_of[fourd.point_key(point)] for point in shape["vertices"]]
    rotated = fourd.rotate_points(fourd.rotation_matrix(rotation), shape["vertices"])
    projected = fourd.project_points(rotated, projection, eye_distance=eye)
    if style == "lines":
        return fourd.line_mesh(projected, shape["edges"], colours)
    return fourd.wireframe_mesh(projected, shape["edges"], radius, None, sides, colours)


def export(path, rotation="xw=0.4,yz=0.25", projection="perspective", eye=2.6, style="tubes", radius=0.022, sides=8):
    """Write the coset-coloured wireframe (.gltf) or the polytope record (.json)."""
    if str(path).endswith(".json"):
        with open(path, "w", encoding="utf-8") as stream:
            json.dump(fourd.polytope_record(polytope(), "24-cell"), stream, indent=1)
            stream.write("\n")
        return {"path": str(path), "f_vector": list(fourd.f_vector(polytope()))}
    mesh = wireframe(rotation, projection, eye, style, radius, sides)
    document = fourd.gltf_document([dict(mesh, name="24cell")], generator="icositetrachoron_24cell.py")
    return {"path": str(path), "bytes": fourd.write_gltf(path, document), **fourd.gltf_summary(document)}


def invariants():
    shape = polytope()
    report = fourd.regularity_report(shape)
    counts = fourd.f_vector(shape)
    groups = cosets()
    units = hurwitz_units()
    return {"vertices": counts[0], "edges": counts[1], "faces": counts[2], "cells": counts[3],
            "euler_characteristic": fourd.euler_characteristic(shape), "circumradius": report["circumradius"],
            "edge_length": report["edge_length"], "regular": report["regular"],
            "schlafli": list(fourd.schlafli_symbol(shape)), "hypervolume": fourd.hypervolume(shape),
            "cell_volume": fourd.cell_volume(shape, 0), "vertex_degree": report["degrees"][0],
            "group_order": len(units), "group_closed": is_group(units), "cosets": len(groups),
            "cosets_are_16cells": [is_sixteen_cell([fourd.quaternion_to_point(e) for e in coset]) for coset in groups],
            "self_dual": is_24cell(dual_vertices())}


def controls():
    shape = polytope()
    moved = dict(shape, vertices=[fourd.add(shape["vertices"][0], (0.03, 0.0, 0.0, 0.0))] + shape["vertices"][1:])
    root2 = 2 ** -0.5
    larger = closure(GENERATORS + ((root2, root2, 0.0, 0.0),))
    groups = cosets()
    swapped = [fourd.quaternion_to_point(e) for e in groups[0][:7] + groups[1][:1]]
    half = hurwitz_units()[:23]

    def refused(action):
        try:
            action()
        except ValueError:
            return True
        return False

    return {"moved_vertex_not_regular": not fourd.regularity_report(moved)["regular"],
            "extra_generator_gives_48_not_24cell": len(larger) == 48 and not is_24cell(
                [fourd.quaternion_to_point(e) for e in larger]),
            "swapped_coset_member_not_16cell": not is_sixteen_cell(swapped),
            "missing_element_not_a_group": not is_group(half),
            "non_unit_generator_refused": refused(lambda: closure(((2.0, 0.0, 0.0, 0.0),)))}


def main(argv=None):
    parser = argparse.ArgumentParser(prog="icositetrachoron_24cell.py",
                                     description="Write the 24-cell built from the Hurwitz units.")
    parser.add_argument("--rotate", default="xw=0.4,yz=0.25", help="plane rotations applied in order, like xw=0.4,yz=15deg")
    parser.add_argument("--project", choices=fourd.PROJECTIONS, default="perspective", help="4D to 3D projection")
    parser.add_argument("--eye", type=float, default=2.6, help="4D eye distance (circumradius is 1)")
    parser.add_argument("--style", choices=("tubes", "lines"), default="tubes", help="tube mesh or LINES primitive")
    parser.add_argument("--radius", type=float, default=0.022, help="tube radius")
    parser.add_argument("--sides", type=int, default=8, help="sides of each tube (3 or more)")
    parser.add_argument("--out", required=True, help=".gltf wireframe or .json polytope record")
    args = parser.parse_args(argv)
    if args.sides < 3 or args.eye <= 0 or args.radius <= 0:
        parser.error("sides is 3 or more; eye and radius are positive")
    try:
        summary = export(args.out, args.rotate, args.project, args.eye, args.style, args.radius, args.sides)
    except ValueError as error:
        parser.error(str(error))
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
