"""Author six contract/case populations before implementing any candidate tool."""
from pathlib import Path
import hashlib
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = Path('/home/username/.le-codex-build/integration')
UNICODE_VERSION = subprocess.check_output(['/usr/bin/python3','-c','import unicodedata; print(unicodedata.unidata_version)'],text=True).strip()
ID = {'type':'string','minLength':1,'maxLength':128,'not':{'pattern':r'[\u0000-\u001f\u007f]'}}
PATH = {'type':'string','minLength':1,'maxLength':256,'pattern':r'^(?!/)(?!.*(?:^|/)\.\.?(/|$))(?!.*//)(?!.*\\)(?!.*[\u0000-\u001f\u007f])[^/]+(?:/[^/]+)*$'}
DIGEST = {'type':'string','pattern':'^[0-9a-f]{64}$','minLength':64,'maxLength':64}
BOOL = {'type':'boolean'}
def integer(low=0,high=9007199254740991):return {'type':'integer','minimum':low,'maximum':high}
def array(items,n,unique=False):
 d={'type':'array','items':items,'maxItems':n}
 if unique:d['uniqueItems']=True
 return d
def obj(fields,optional=()):return {'type':'object','properties':fields,'required':[k for k in fields if k not in optional],'additionalProperties':False}
def sha(s):return hashlib.sha256(s.encode('utf-8')).hexdigest()
def req(name,**fields):return {'record_type':name+'_request/v1',**fields}
def out(name,**fields):return {'record_type':name+'_result/v1',**fields}
def case(name,value,expected,code=0):return {'name':name,'input':value,'expected':expected,'expected_exit':code}
def bad(name,value,error='invalid_input'):return case(name,value,{'error':error},2)
def raw(name,text,error='invalid_input'):return {'name':name,'raw_input':text,'expected':{'error':error},'expected_exit':2}
def package(identity,title,purpose,fields,result,cases,notes,tags,optional=(),errors=()):
 folder=ROOT/identity
 for part in ('contracts','examples','verification','tools'): (folder/part).mkdir(parents=True,exist_ok=True)
 input_schema={'$schema':'https://json-schema.org/draft/2020-12/schema','title':title+' input',**obj({'record_type':{'const':identity+'_request/v1'},**fields},optional)}
 input_schema['description']='Strict UTF-8 JSON document, at most 65536 bytes and 16 container levels; duplicate keys, nonfinite literals and lone surrogates refuse. Numeric literals at most 128 characters; mathematically integral decimal/scientific numbers are accepted exactly. Additional semantic conditions are stated in AGENTS.md.'
 success=obj({'record_type':{'const':identity+'_result/v1'},**result})
 error=obj({'error':{'enum':['invalid_input','output_limit_exceeded',*errors]}})
 output_schema={'$schema':'https://json-schema.org/draft/2020-12/schema','title':title+' output','oneOf':[success,error], 'description':'Exactly one UTF-8 JSON line, at most 131072 bytes including LF. Success exits 0; refusal exits 2. No diagnostic content is sent to stderr.'}
 cases += [raw('duplicate_top_key','{"record_type":"'+identity+'_request/v1","record_type":"'+identity+'_request/v1"}'),raw('nonfinite','{"x":NaN}'),raw('depth_limit','['*17+'0'+']'*17),raw('lone_surrogate','{"x":"\\ud800"}'),bad('unknown_top_field',{**cases[0]['input'],'unrecognized':True})]
 for relative,value in [('contracts/input.schema.json',input_schema),('contracts/output.schema.json',output_schema),('examples/input.json',cases[0]['input']),('examples/output.json',cases[0]['expected']),('verification/cases.json',cases)]:
  target=folder/relative
  if target.exists():raise RuntimeError('Existing contract/case file: '+str(target))
  target.write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n')
 (folder/'LICENSE').write_bytes((CANONICAL/'LICENSE').read_bytes())
 brief=f'''# {title}\n\nCandidate harness intelligence. Native loading and usefulness are not qualified.\n\n## Task\n\n{purpose}\n\n## First steps\n\n1. Read `contracts/input.schema.json` and the semantic rules below.\n2. Construct one bounded JSON request from supplied data.\n3. With host permission to start the interpreter, run `python3 tools/{identity}.py` and supply the request on standard input.\n4. Check the exit code and `contracts/output.schema.json`; compare the result with the task's acceptance conditions.\n\nThe command returns one JSON line: exit 0 for a result, exit 2 for a refusal.\nThe input is at most 65536 UTF-8 bytes and 16 container levels. JSON duplicate\nkeys, nonfinite numbers, invalid Unicode scalars and unknown fields refuse.\nNumeric literals are at most 128 characters; integral forms such as 1.0 and\n1e0 are accepted without binary-float rounding. Booleans are not integers.\nThe output limit is 131072 UTF-8 bytes including its trailing newline; an\noversized result returns `output_limit_exceeded`. Schemas describe shape and\nfield bounds; wire limits and cross-field conditions are additional rules.\n\n## Method and limits\n\n{notes}\n\n## Authority and dependencies\n\nPython 3.10 or newer, standard library only. The method reads supplied standard\ninput and writes standard output. It performs no task-file access, network\nrequest, subprocess launch, environment lookup or dynamic import. The host's\ninterpreter launch is a separate `spawns_process` effect. Paths and labels are\ndata; no result grants execution, installation, publication or access authority.\nNo current workspace, package catalogue or live filesystem state is inferred.\n\n## Verification\n\nUse the synthetic example and `verification/cases.json`. Structural success\nis separate from semantic usefulness and independent review. This candidate\nis original Codex/OpenAI-family material under the repository MIT notice;\nno third-party content is claimed licensed by that notice.\n'''
 (folder/'AGENTS.md').write_text(brief)
 METADATA[identity]={'title':title,'purpose':purpose,'search_tags':tags,'dependencies':[{'name':'Python','version':'>=3.10','scope':'interpreter','standard_library_only':True}], 'declared_effects':['spawns_process'],'sourcebasis':{'kind':'first_party_original','producer':'Codex','producer_family':'openai','method_identity':'codex_original_working_directory_components/v1','canonical_source_revision':'231f51bb1facab517fbe915b08ea9ac85f913347','framing_reuse':'First-party bounded JSON framing from artifacts/mixed-native-originals-contract-v2-2026-09-23/author_packages.py; algorithms authored for these contracts; no outside implementation copied.'},'limits':{'input_utf8_bytes':65536,'output_utf8_bytes_including_lf':131072,'container_depth':16,'numeric_literal_characters':128},'methodinterface':{'record_type':'bounded_json_cli_method/v1','input_record_type':identity+'_request/v1','output_record_type':identity+'_result/v1','entrypoint':'tools/'+identity+'.py','input':'UTF-8 JSON stdin','output':'UTF-8 JSON stdout plus LF','success_exit':0,'refusal_exit':2,'error_codes':['invalid_input','output_limit_exceeded',*errors]},'status':'candidate','native_qualification':'unqualified','approved':False}

METADATA={}
a,b,c='a'*64,'b'*64,'c'*64
entry=lambda path,digest=a,size=1,execute=False:{'path':path,'digest':digest,'size_bytes':size,'executable':execute}
n='compare_file_inventories';fields={'before':array(obj({'path':PATH,'digest':DIGEST,'size_bytes':integer(),'executable':BOOL}),256),'after':array(obj({'path':PATH,'digest':DIGEST,'size_bytes':integer(),'executable':BOOL}),256)}
cases=[case('changed_added_removed',req(n,before=[entry('same'),entry('old'),entry('changed')],after=[entry('new'),entry('same'),entry('changed',b,2,True)]),out(n,added=['new'],removed=['old'],unchanged=['same'],changed=[{'path':'changed','fields':['digest','size_bytes','executable']}])),case('rename_not_inferred',req(n,before=[entry('a')],after=[entry('b')]),out(n,added=['b'],removed=['a'],changed=[],unchanged=[])),case('empty',req(n,before=[],after=[]),out(n,added=[],removed=[],changed=[],unchanged=[])),case('integral_metadata',req(n,before=[entry('é',size=1.0)],after=[entry('é',size=1)]),out(n,added=[],removed=[],changed=[],unchanged=['é'])),bad('duplicate_path',req(n,before=[entry('a'),entry('a')],after=[])),bad('unknown_entry_field',req(n,before=[{**entry('a'),'role':'tool'}],after=[])),bad('traversal',req(n,before=[entry('a/../b')],after=[])),bad('bool_not_size',req(n,before=[entry('a',size=True)],after=[])),bad('bad_digest',req(n,before=[entry('a',digest='A'*64)],after=[]))]
package(n,'Compare supplied file inventories','Compare two explicit file inventories by exact relative path and supplied SHA-256, size and executable metadata. Report changes without reading files or guessing renames.',fields,{'added':array(PATH,256),'removed':array(PATH,256),'unchanged':array(PATH,256),'changed':array(obj({'path':PATH,'fields':array({'enum':['digest','size_bytes','executable']},3,True)}),256)},cases,'Each side has at most 256 entries and distinct exact paths. Relative POSIX-style paths have no leading/trailing slash, empty segment, dot/dot-dot segment, backslash or control character; maximum 256 Unicode codepoints. Paths are compared case-sensitively without normalization. Output lists are sorted by Unicode codepoint order; changed fields use digest, size_bytes, executable order. Identical digests at different paths remain removal/addition, never a guessed rename. Supplied digests and metadata are not checked against physical files. Parent/file feasibility is not decided here.',['inventory','file_manifest','digest_diff','metadata','deterministic'])

n='resolve_selected_dependency_closure';node=obj({'id':ID,'requires':array(ID,16,True)})
fields={'roots':array(ID,256,True),'packages':array(node,256)}
cyclegraph=[{'id':'a','requires':['b']},{'id':'b','requires':['a','c']},{'id':'c','requires':['c']},{'id':'ignored','requires':['absent']}]
cases=[case('selected_transitive_closure',req(n,roots=['a'],packages=[{'id':'a','requires':['b']},{'id':'b','requires':['c']},{'id':'c','requires':[]},{'id':'unused','requires':[]}]),out(n,selected=['a','b','c'],cyclic_components=[])),case('reachable_cycles_reported',req(n,roots=['a'],packages=cyclegraph),out(n,selected=['a','b','c'],cyclic_components=[['a','b'],['c']])),case('unreachable_missing_ignored',req(n,roots=['ok'],packages=[{'id':'ok','requires':[]},{'id':'unused','requires':['absent']}]),out(n,selected=['ok'],cyclic_components=[])),case('no_selection',req(n,roots=[],packages=cyclegraph),out(n,selected=[],cyclic_components=[])),bad('missing_reachable',req(n,roots=['a'],packages=[{'id':'a','requires':['missing']}]),'missing_dependency'),bad('missing_root',req(n,roots=['missing'],packages=[]),'missing_dependency'),bad('duplicate_package',req(n,roots=[],packages=[{'id':'a','requires':[]},{'id':'a','requires':[]}]))]
package(n,'Resolve an exact selected dependency closure','Find the transitive closure of selected exact package IDs and report cycles; refuse a missing reachable dependency without choosing versions or downloading material.',fields,{'selected':array(ID,256,True),'cyclic_components':array(array(ID,256,True),256)},cases,'Package IDs are unique, exact case-sensitive Unicode strings. Roots and each requires list contain no duplicate ID. At most 256 packages, 256 roots and 16 direct requirements per package. Only the selected closure must resolve: an unselected package may refer to an absent ID. A missing root or reached dependency returns missing_dependency. The selected list is sorted; cyclic_components are strongly connected groups of size greater than one or self-loop singletons, each sorted and then lexicographically ordered. This is a selection report, not a topological install order, semantic-version solver, provider selector or compiler.',['dependency_graph','closure','selected_packages','missing_dependency','cycles'],errors=('missing_dependency',))

n='assign_digest_shards';fields={'ids':array(ID,1024,True),'shard_count':integer(1,4096)}
assign=lambda ids,count:out(n,shard_count=count,assignments=[{'id':i,'sha256':sha(i),'shard':int(sha(i),16)%count} for i in sorted(ids)])
cases=[case('known_hashes',req(n,ids=['b','a','abc'],shard_count=7),assign(['b','a','abc'],7)),case('unicode_bytes_not_normalized',req(n,ids=['é','e\u0301'],shard_count=13),assign(['é','e\u0301'],13)),case('one_shard',req(n,ids=['x'],shard_count=1.0),assign(['x'],1)),case('empty_ids',req(n,ids=[],shard_count=4),assign([],4)),bad('zero_shards',req(n,ids=['x'],shard_count=0)),bad('bool_shards',req(n,ids=['x'],shard_count=True)),bad('duplicate_id',req(n,ids=['x','x'],shard_count=2)),bad('unicode_output_byte_limit',req(n,ids=[str(i).zfill(4)+'😀'*10 for i in range(1000)],shard_count=4096),'output_limit_exceeded')]
package(n,'Assign exact IDs to digest shards','Assign supplied IDs to a fixed shard count using the entire SHA-256 digest of each exact UTF-8 ID modulo the shard count.',fields,{'shard_count':integer(1,4096),'assignments':array(obj({'id':ID,'sha256':DIGEST,'shard':integer(0,4095)}),1024)},cases,'At most 1024 distinct IDs. Sort IDs by Unicode codepoint order for output. Hash the exact UTF-8 bytes, without Unicode normalization, salting or case changes. Interpret all 32 SHA-256 bytes as one unsigned big-endian integer and take modulo shard_count (1..4096). An integral numeric spelling such as 1.0 is accepted. Changing the shard count may move many IDs: this is not consistent hashing, a balance guarantee, a cryptographic authorization or a storage allocation.',['sha256','sharding','partition_assignment','fixed_bucket_count','utf8'])

n='validate_event_precedence';fields={'events':array(ID,1024,True),'constraints':array(obj({'before':ID,'after':ID}),2048,True)}
v=lambda before,after,i,j,reason:{'before':before,'after':after,'before_index':i,'after_index':j,'reason':reason}
cases=[case('strict_order',req(n,events=['fetch','verify','use'],constraints=[{'before':'fetch','after':'verify'},{'before':'verify','after':'use'}]),out(n,satisfied=True,violations=[])),case('reverse_and_self',req(n,events=['a','b'],constraints=[{'before':'b','after':'a'},{'before':'a','after':'a'}]),out(n,satisfied=False,violations=[v('b','a',1,0,'not_before'),v('a','a',0,0,'not_before')])),case('missing_event_report',req(n,events=['a'],constraints=[{'before':'missing','after':'a'},{'before':'x','after':'y'}]),out(n,satisfied=False,violations=[v('missing','a',None,0,'missing_event'),v('x','y',None,None,'missing_event')])),case('empty_constraints',req(n,events=[],constraints=[]),out(n,satisfied=True,violations=[])),bad('ambiguous_repeated_event',req(n,events=['a','a'],constraints=[])),bad('duplicate_constraint',req(n,events=['a','b'],constraints=[{'before':'a','after':'b'},{'before':'a','after':'b'}]))]
package(n,'Validate declared event precedence','Check strictly-before constraints against one supplied event-ID sequence, reporting missing IDs and order violations without inferring causality or using timestamps.',fields,{'satisfied':BOOL,'violations':array(obj({'before':ID,'after':ID,'before_index':{'anyOf':[integer(0,1023),{'type':'null'}]},'after_index':{'anyOf':[integer(0,1023),{'type':'null'}]},'reason':{'enum':['missing_event','not_before']}}),2048)},cases,'Event IDs are unique and exact; repeated IDs refuse rather than selecting an occurrence. Constraints are unique ordered pairs. At most 1024 events and 2048 constraints. Indices are zero-based. before_index must be strictly less than after_index; a self-constraint is unsatisfied. Missing endpoints produce missing_event with null indices. Violations retain input constraint order. Empty constraints are satisfied. This checks only declared sequence obligations, not actual event occurrence, time or causal order.',['event_sequence','precedence','validation','before_after','workflow_evidence'])

n='apply_nonoverlapping_text_edits';edit=obj({'start':integer(0,32768),'end':integer(0,32768),'replacement':{'type':'string','maxLength':8192}});fields={'text':{'type':'string','maxLength':32768},'edits':array(edit,128),'expected_sha256':DIGEST}
result=lambda source,text,count:out(n,text=text,source_sha256=sha(source),result_sha256=sha(text),edits_applied=count)
cases=[case('simultaneous_original_positions',req(n,text='abcdef',edits=[{'start':4,'end':6,'replacement':'Y'},{'start':1,'end':3,'replacement':'X'}],expected_sha256=sha('abcdef')),result('abcdef','aXdY',2)),case('unicode_codepoint_offsets',req(n,text='é🙂z',edits=[{'start':1.0,'end':2.0,'replacement':'!'}]),result('é🙂z','é!z',1)),case('insertion_at_previous_end',req(n,text='ab',edits=[{'start':0,'end':1,'replacement':'X'},{'start':1,'end':1,'replacement':'!'}]),result('ab','X!b',2)),case('empty_edit_set',req(n,text='unchanged',edits=[]),result('unchanged','unchanged',0)),case('empty_source_insertion',req(n,text='',edits=[{'start':0,'end':0,'replacement':'hi'}]),result('','hi',1)),bad('overlapping_ranges',req(n,text='abc',edits=[{'start':0,'end':2,'replacement':''},{'start':1,'end':3,'replacement':''}]),'overlapping_edits'),bad('same_start_insertions',req(n,text='abc',edits=[{'start':1,'end':1,'replacement':'x'},{'start':1,'end':1,'replacement':'y'}]),'overlapping_edits'),bad('insertion_at_replacement_start',req(n,text='abc',edits=[{'start':1,'end':1,'replacement':'x'},{'start':1,'end':2,'replacement':'y'}]),'overlapping_edits'),bad('wrong_source_digest',req(n,text='abc',edits=[],expected_sha256='0'*64),'source_digest_mismatch'),bad('out_of_range',req(n,text='a',edits=[{'start':0,'end':2,'replacement':''}]))]
package(n,'Apply simultaneous nonoverlapping text edits','Apply a bounded batch of edits against the original string using Unicode-codepoint positions, optionally checking its exact UTF-8 SHA-256 first.',fields,{'text':{'type':'string'},'source_sha256':DIGEST,'result_sha256':DIGEST,'edits_applied':integer(0,128)},cases,'Offsets are zero-based Unicode codepoints, not UTF-8 bytes, UTF-16 units, grapheme clusters or line numbers. Every interval is half-open and must satisfy 0 <= start <= end <= len(original text). Sort by (start,end); positive overlaps and any repeated start position refuse as overlapping_edits. An insertion inside a replaced interval refuses; an insertion exactly at the preceding interval end is allowed unless another edit starts there. Edits are simultaneous against the original string, never sequential shifted coordinates. A supplied expected_sha256 must match the original UTF-8 bytes before editing. No Unicode normalization, patch search, fuzzy anchoring or file write occurs.',['text_edit','simultaneous_edits','unicode_codepoints','digest_anchor','nonoverlap'],optional=('expected_sha256',),errors=('source_digest_mismatch','overlapping_edits'))

n='detect_portable_path_collisions';fields={'paths':array(PATH,256),'platform_model':{'const':'unicode_nfc_casefold/v1'},'expected_unicode_version':{'type':'string','minLength':1,'maxLength':32}}
response=lambda collisions,parents:out(n,platform_model='unicode_nfc_casefold/v1',unicode_version=UNICODE_VERSION,collision_free=not collisions and not parents,collisions=collisions,parent_file_collisions=parents)
group=lambda name,indices,paths:{'normalized_path':name,'indices':indices,'paths':paths}
parent=lambda a,b,ia,ib:{'parent':a,'child':b,'parent_indices':ia,'child_indices':ib}
cases=[case('unicode_case_and_parent',req(n,paths=['Straße','STRASSE','A','a/child'],platform_model='unicode_nfc_casefold/v1'),response([group('strasse',[0,1],['Straße','STRASSE'])],[parent('a','a/child',[2],[3])])),case('canonical_equivalence',req(n,paths=['é.txt','e\u0301.txt'],platform_model='unicode_nfc_casefold/v1'),response([group('é.txt',[0,1],['é.txt','e\u0301.txt'])],[])),case('exact_duplicate_is_reported',req(n,paths=['a','a'],platform_model='unicode_nfc_casefold/v1'),response([group('a',[0,1],['a','a'])],[])),case('all_ancestor_pairs',req(n,paths=['a','a/b','a/b/c'],platform_model='unicode_nfc_casefold/v1'),response([],[parent('a','a/b',[0],[1]),parent('a','a/b/c',[0],[2]),parent('a/b','a/b/c',[1],[2])])),case('fullwidth_is_not_nfkc',req(n,paths=['A','Ａ'],platform_model='unicode_nfc_casefold/v1'),response([],[])),case('reserved_name_not_security_verdict',req(n,paths=['CON'],platform_model='unicode_nfc_casefold/v1'),response([],[])),bad('unicode_version_mismatch',req(n,paths=[],platform_model='unicode_nfc_casefold/v1',expected_unicode_version='0.0.0'),'unicode_version_mismatch'),bad('wrong_model',req(n,paths=[],platform_model='windows')),bad('dot_component',req(n,paths=['a/./b'],platform_model='unicode_nfc_casefold/v1'))]
package(n,'Detect abstract portable path collisions','Report exact, Unicode-normalization/casefold and parent-file path collisions under one explicitly named abstract comparison model.',fields,{'platform_model':{'const':'unicode_nfc_casefold/v1'},'unicode_version':{'type':'string'},'collision_free':BOOL,'collisions':array(obj({'normalized_path':{'type':'string'},'indices':array(integer(0,255),256),'paths':array(PATH,256)}),256),'parent_file_collisions':array(obj({'parent':{'type':'string'},'child':{'type':'string'},'parent_indices':array(integer(0,255),256),'child_indices':array(integer(0,255),256)}),1024)},cases,'The model applies NFC, casefold, then NFC to each slash-separated segment. The returned Unicode database version is the runtime version; optional expected_unicode_version must match it. This is not NFKC, locale collation, NTFS/APFS/ext4 emulation, Windows reserved-name validation or a filesystem-security guarantee. Input paths are explicit files; a normalized path that prefixes another at a slash is a parent-file collision. Exact duplicates are accepted and reported by their original indices. Groups sort by normalized path; all ancestor/descendant pairs sort by (parent,child). More than 1024 parent-file pairs refuses as output_limit_exceeded. No directories, symlinks, permissions, case behavior or files on disk are inspected.',['portable_paths','unicode_normalization','casefold','path_collision','parent_file_conflict'],optional=('expected_unicode_version',),errors=('unicode_version_mismatch',))

(ROOT/'authors/systems-metadata.json').write_text(json.dumps(METADATA,indent=2,ensure_ascii=False)+'\n')
(ROOT/'authors/contracts-first.json').write_text(json.dumps({'record_type':'original_contract_population/v1','stage':'contracts_and_cases_before_implementation','packages':list(METADATA),'tool_files_present':list(str(p) for p in ROOT.glob('*/tools/*.py')),'unicode_version_for_fixtures':UNICODE_VERSION},indent=2)+'\n')
print(json.dumps({'packages':list(METADATA),'tool_files_present':list(str(p) for p in ROOT.glob('*/tools/*.py')),'unicode_version':UNICODE_VERSION}))
