"""Frozen examples and domains for original creative components.

Examples are independently specified values, not answers generated by the
implementation being tested. Broader visual and engine qualification is separate.
"""

# name: (domain, successful [arguments, expected] cases, rejected argument cases)
CASES = {
    "smoothstep": ("motion", [([0], 0), ([0.25], 0.15625), ([1], 1)], [[-0.1], [1.1]]),
    "smootherstep": ("motion", [([0], 0), ([0.25], 0.103515625), ([1], 1)], [[-1], [2]]),
    "quadratic_in": ("motion", [([0], 0), ([0.5], 0.25), ([1], 1)], [[-1], [2]]),
    "quadratic_out": ("motion", [([0], 0), ([0.5], 0.75), ([1], 1)], [[-1], [2]]),
    "cubic_in": ("motion", [([0], 0), ([0.5], 0.125), ([1], 1)], [[-1], [2]]),
    "cubic_out": ("motion", [([0], 0), ([0.5], 0.875), ([1], 1)], [[-1], [2]]),
    "sine_in_out": ("motion", [([0], 0), ([0.5], 0.5), ([1], 1)], [[-1], [2]]),
    "ping_pong": ("motion", [([0.25], 0.5), ([0.5], 1), ([1], 0), ([-0.25], 0.5)], []),
    "linear_mix": ("motion", [([2, 10, 0.25], 4), ([5, 7, 1], 7)], [[2, 3, 2]]),
    "quadratic_bezier": ("geometry", [([0, 2, 4, 0.5], 2), ([1, 2, 7, 0], 1)], [[1, 2, 3, 2]]),
    "cubic_bezier": ("geometry", [([0, 0, 8, 8, 0.5], 4), ([1, 2, 3, 4, 1], 4)], [[1, 2, 3, 4, -1]]),
    "frame_time": ("timeline", [([30, 30], 1), ([1001, 30000], 0.03336666666666667)], [[1.5, 30], [-1, 30], [1, 0]]),
    "beat_time": ("audio", [([4, 120], 2), ([0, 60], 0)], [[-1, 120], [1, 0]]),
    "segment_progress": ("timeline", [([1, 2, 4], 0), ([4, 2, 4], 0.5), ([9, 2, 4], 1)], [[0, 0, 0]]),
    "fit_inside": ("layout", [([1920, 1080, 1000, 1000], [0, 218.75, 1000, 562.5])], [[0, 1, 1, 1]]),
    "cover_frame": ("layout", [([100, 50, 200, 200], [-100, 0, 400, 200])], [[1, -1, 1, 1]]),
    "rotate_point": ("geometry", [([1, 0, 1.5707963267948966], [0, 1]), ([2, 3, 0], [2, 3])], []),
    "orbit_point": ("camera", [([2, 0, 3], [2, 3, 0]), ([1, 3.141592653589793, 0], [-1, 0, 0])], [[0, 0, 0]]),
    "circle_distance": ("geometry", [([3, 4, 2], 3), ([0, 0, 2], -2)], [[0, 0, 0]]),
    "sphere_distance": ("geometry", [([2, 3, 6, 2], 5), ([0, 0, 0, 3], -3)], [[0, 0, 0, -1]]),
    "normalize_three": ("geometry", [([3, 4, 0], [0.6, 0.8, 0]), ([0, 0, -2], [0, 0, -1])], [[0, 0, 0]]),
    "cross_three": ("geometry", [([1, 0, 0, 0, 1, 0], [0, 0, 1]), ([0, 1, 0, 1, 0, 0], [0, 0, -1])], []),
    "wrap_angle": ("geometry", [([0], 0), ([3.141592653589793], -3.141592653589793)], []),
    "jump_velocity": ("physics", [([5, 10], 10), ([2, 9], 6)], [[0, 10], [1, 0]]),
    "ballistic_height": ("physics", [([10, 10, 1], 5), ([10, 10, 2], 0)], [[1, 0, 1], [1, 1, -1]]),
    "linear_drag": ("physics", [([12, 0, 10], 12), ([10, 1, 1], 3.6787944117144233)], [[1, -1, 1], [1, 1, -1]]),
    "critical_step": ("motion", [([0, 2], 0), ([1, 1], 0.26424111765711533)], [[-1, 1], [1, 0]]),
    "midi_frequency": ("audio", [([69], 440), ([81], 880), ([57], 220)], [[-1], [128]]),
    "amplitude_to_db": ("audio", [([1], 0), ([10], 20), ([0.1], -20)], [[0], [-1]]),
    "db_to_amplitude": ("audio", [([0], 1), ([20], 10), ([-20], 0.1)], [[601], [-601]]),
    "equal_power_pan": ("audio", [([-1], [1, 0]), ([1], [0, 1]), ([0], [0.7071067811865476, 0.7071067811865476])], [[-2], [2]]),
    "alpha_over": ("color", [([0.5, 0.5], 0.75), ([0, 1], 1), ([1, 0], 1)], [[-1, 0], [0, 2]]),
    "srgb_to_linear": ("color", [([0], 0), ([1], 1), ([0.5], 0.21404114048223255)], [[-1], [2]]),
    "linear_to_srgb": ("color", [([0], 0), ([1], 1), ([0.21404114048223255], 0.5)], [[-1], [2]]),
    "contrast_ratio": ("color", [([0, 1], 21), ([0.5, 0.5], 1)], [[-1, 0], [0, 2]]),
}

# Units form part of the contract; adapters must not infer them from labels.
UNITS = {
    "frame": "frame_index", "rate": "frames_per_second", "time": "seconds", "start": "seconds",
    "duration": "seconds", "beat": "beats", "bpm": "beats_per_minute", "angle": "radians",
    "phase": "cycles", "gravity": "length_per_second_squared", "velocity": "length_per_second",
    "drag": "inverse_seconds", "omega": "radians_per_second", "note": "midi_note",
    "db": "amplitude_decibels", "pan": "normalized_pan", "amplitude": "linear_amplitude",
    "t": "normalized_progress", "channel": "normalized_channel", "light": "relative_luminance",
    "dark": "relative_luminance", "foreground": "alpha_coverage", "background": "alpha_coverage",
}

UNIT_INTERVAL = {"t", "channel", "light", "dark", "foreground", "background"}
POSITIVE = {"rate", "duration", "bpm", "radius", "width", "height", "frame_width", "frame_height",
            "gravity", "omega", "amplitude"}


def input_property(component, name):
    """JSON Schema for one numeric port, plus its non-inferred unit."""
    value = {"type": "integer" if name == "frame" else "number",
             "description": UNITS.get(name, "shared_coordinate_unit")}
    if name in UNIT_INTERVAL:
        value.update(minimum=0, maximum=1)
    if name in POSITIVE and not (component == "orbit_point" and name == "height"):
        value.update(exclusiveMinimum=0)
    if name in ("frame", "beat", "drag") or name == "time" and component in (
            "ballistic_height", "linear_drag", "critical_step"):
        value.update(minimum=0)
    if name == "note":
        value.update(minimum=0, maximum=127)
    if name == "db":
        value.update(minimum=-600, maximum=600)
    if name == "pan":
        value.update(minimum=-1, maximum=1)
    return value
