#!/usr/bin/env python3
"""Build supply lines of executable library components and store them as candidates in the import store.

See tools/supply_lines/README.md. Each command reads pinned public facts,
generates packages deterministically (no model call), checks them and, only
with --authorize-store-writes, writes them to the import store's supply
namespace through the importer's write path. Nothing is approved, served or
published.

```text
build_library_supply.py
├── mcp-registry   one protocol server connection per server of the official registry
├── openapi        one API operation client per operation of a licensed OpenAPI specification
├── openapi-directory  the same for every APIs.guru specification whose own licence allows copying
├── openapi-discovery  the same for every Google API discovery document of Google's Apache-2.0 client
├── programs       one install recipe with a typed wrapper per command-line program
├── data-tables    one reference data table with its schema, loader and tests
├── publisher-tables  one data table per series or table of an official publisher's own address
│                  (World Development Indicators, the O*NET 31.0 Database), its licence decided per
│                  series or release from the publisher's own statement, with proposed SDG goals
├── functions      one documented function of a permissively licensed library, with the code it needs
├── schemas        one SchemaStore JSON Schema with a validator and its own examples as tests
├── curated-schemas  one JSON Schema of a curated repository (json_schema_sources.json), with tests
├── api-schemas    one JSON Schema per named object of a curated OpenAPI specification, with tests
├── manim-scenes   one tested animation scene per example scene of Manim Community's documentation
├── api-tool-servers  one tested Model Context Protocol tool server per curated OpenAPI specification file
└── report         the supply by family and form, and the projected composition
```

Network reads need --authorize-network-reads; store writes need
--authorize-store-writes. Run folders and every generated byte stay outside
the repository, under /home/username/baltor-library/supply/<line>/<date>/.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
for entry in (str(HERE), str(ROOT / "src")):
    if entry not in sys.path:
        sys.path.insert(0, entry)

from loop_engine.core.library_ingestion.record_rules import now_utc  # noqa: E402

from supply_lines import records  # noqa: E402
from supply_lines.reading import FactReader  # noqa: E402

LICENCE_FILE = ROOT / "LICENSE"
#: The code the generators run: a stored package must name a revision where all of it is committed. Generated
#: views elsewhere in the tree (a regenerated status page) do not change what a generator writes.
GENERATOR_PATHS = ("tools/supply_lines", "tools/build_library_supply.py", "tools/licensed_import",
                   "tools/component_qualification",
                   "src/loop_engine/core/library_ingestion", "src/loop_engine/core/service_runtime/catalogue_attributes.py",
                   "src/loop_engine/core/service_runtime/catalogue_packages.py", "src/loop_engine/data/library_composition.json",
                   "LICENSE")


def code_revision(storing: bool) -> str:
    """The committed revision of this tool. Stored packages must name a revision their generator can be read
    from, so a store write with uncommitted generator code is refused; a trial run marks the revision."""
    revision = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"], capture_output=True, text=True,
                              check=True).stdout.strip()
    dirty = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain", "--", *GENERATOR_PATHS],
                           capture_output=True, text=True, check=True).stdout
    if dirty.strip():
        if storing:
            raise SystemExit("the supply line code has uncommitted changes; commit it so the packages name its "
                             "revision")
        return revision + "+uncommitted"
    return revision


def _outside(path: Path) -> Path:
    path = Path(path).resolve()
    if path == ROOT or ROOT in path.parents:
        raise SystemExit("run folders and generated packages stay outside the repository")
    return path


def materialize(folder: Path, built) -> None:
    """Write each package's files under folder/<record id>/ for inspection and local test runs."""
    for payload, bodies in built:
        root = folder / payload["record_id"]
        for entry in payload["package"]["files"]:
            target = root / entry["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(bodies[entry["digest"]])
        (root / "candidate.json").write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n", encoding="utf-8")


#: The free space a store write leaves on the store's disk at least (the workstation's standing floor).
MINIMUM_FREE_GIGABYTES = 15
#: How many times a store write is tried while another job holds the store's lock, and the pause between tries.
STORE_ATTEMPTS, STORE_PAUSE_SECONDS = 20, 30


def free_gigabytes(path) -> float:
    """Free space of the disk holding path (its nearest existing parent), in gigabytes."""
    path = Path(path)
    while not path.exists() and path != path.parent:
        path = path.parent
    return shutil.disk_usage(path).free / 1024 ** 3


def store(args, line: str, built, facts: dict, *, complete: bool, scope: str = "") -> dict:
    if not args.authorize_store_writes:
        return {"stored": False, "reason": "no --authorize-store-writes"}
    free = free_gigabytes(args.store_root)
    if free < args.minimum_free_gigabytes:
        # The run's facts stay cached in its run folder, so the same command stores quickly once space returns.
        return {"stored": False, "reason": "free_space_below_the_floor", "free_gigabytes": round(free, 1),
                "floor_gigabytes": args.minimum_free_gigabytes}
    from loop_engine.catalog.protocol import StoreError
    from supply_lines.store import SupplyStore
    # The import store is one SQLite file other jobs write too; opening it or applying a batch while another
    # writer holds the lock fails after a five-second wait. A batch is atomic and bodies are stored by digest, so
    # the whole write is tried again after a pause, a bounded number of times.
    for attempt in range(STORE_ATTEMPTS):
        try:
            writer = SupplyStore(args.store_root, writes_authorized=True)
            try:
                kept = writer.keep_facts(facts)
                result = writer.write(line, built, complete=complete, scope=scope)
            finally:
                writer.close()
            return {"stored": True, "facts_kept": kept, "attempts": attempt + 1, **result}
        except StoreError as error:
            if attempt == STORE_ATTEMPTS - 1:
                return {"stored": False, "reason": "store_busy", "detail": str(error)[:200], "attempts": attempt + 1}
            time.sleep(STORE_PAUSE_SECONDS)
    return {"stored": False, "reason": "store_busy"}


def finish(args, line: str, built, refusals, extra: dict, reader, facts: dict, *, complete: bool,
           scope: str = "") -> dict:
    run_folder = Path(args.run_folder)
    if args.materialize:
        materialize(run_folder / "packages", built)
    (run_folder / "refusals.jsonl").write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in refusals),
                                               encoding="utf-8")
    elapsed = round(time.monotonic() - args.started_clock, 1)
    report = {"record_type": records.RUN_RECORD_TYPE, "line": line, "started_at": args.started_at,
              "finished_at": now_utc(), "elapsed_seconds": elapsed,
              "candidates_per_hour": round(len(built) * 3600 / elapsed) if elapsed else None,
              "candidates": len(built), "refused": len(refusals),
              "refused_by_reason": dict(Counter(row["reason"] for row in refusals).most_common()),
              "forms": dict(Counter(payload["component_form"]["form"] for payload, _bodies in built)),
              "licences": dict(Counter(payload["licence"]["spdx_expression"] for payload, _bodies in built)),
              "effects": dict(Counter(effect for payload, _bodies in built for effect in payload["declared_effects"])),
              "requests": reader.requests() if reader else {}, **extra,
              "store": store(args, line, built, facts, complete=complete, scope=scope)}
    (run_folder / f"run-{report['finished_at'].replace(':', '')}.json").write_text(
        json.dumps(report, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({key: report[key] for key in ("line", "candidates", "refused", "elapsed_seconds",
                                                   "candidates_per_hour", "refused_by_reason", "store")},
                     indent=1, default=str))
    return report


def mcp_registry(args) -> dict:
    from supply_lines import mcp_registry as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    entries, refusals, complete, quarantine = line.read_registry(
        reader, run_folder / "quarantine", maximum_entries=args.maximum_entries, maximum_lookups=args.maximum_lookups)
    repositories = sorted({line.upstream_github_repository(entry["server"]) for entry, _source in entries
                           if line.upstream_github_repository(entry["server"]) and line._has_package(entry["server"])})
    facts_by_repository = reader.repository_facts(repositories) if args.stars else {}
    built, generated_refusals = line.generate(entries, reader, code_revision=revision,
                                              licence_text=LICENCE_FILE.read_bytes(), generated_on=now_utc()[:10],
                                              repository_facts=facts_by_repository)
    facts = {}
    for payload, _bodies in built:
        entry_digest = payload["provenance"]["facts"][0]["sha256"]
        facts[entry_digest] = quarantine.get(entry_digest)
    return finish(args, records.MCP_REGISTRY, built, refusals + generated_refusals,
                  {"registry_entries_read": len(entries) + len(refusals), "registry_complete": complete},
                  reader, facts, complete=complete and args.maximum_entries >= 100_000)


def openapi(args) -> dict:
    from supply_lines import openapi_operations as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=128 * 1024 * 1024)
    sources = line.read_sources()
    if args.source:
        sources = [row for row in sources if row["source_id"] in args.source]
    facts_by_repository = reader.repository_facts(sorted({row["repository"] for row in sources})) if args.stars else {}
    built, refusals, facts, summary = line.generate(reader, sources, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging",
                                                    repository_facts=facts_by_repository)
    return finish(args, records.OPENAPI_OPERATIONS, built, refusals, {"specifications": summary}, reader, facts,
                  complete=not args.source)


def openapi_directory(args) -> dict:
    from supply_lines import openapi_directory as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=128 * 1024 * 1024)
    built, refusals, facts, decisions, summary = line.generate(
        reader, code_revision=revision, licence_text=LICENCE_FILE.read_bytes(), generated_on=now_utc()[:10],
        staging=run_folder / "staging", only=args.api, maximum_apis=args.maximum_apis, excluded=args.exclude_api)
    (run_folder / "licences.jsonl").write_text("".join(json.dumps(row, sort_keys=True) + "\n" for row in decisions),
                                                encoding="utf-8")
    licences = Counter((row["decision"], row.get("spdx"), row.get("basis")) for row in decisions)
    return finish(args, records.OPENAPI_OPERATIONS, built, refusals,
                  {"directory": summary, "licence_decisions": [{"decision": decision, "spdx": spdx, "basis": basis,
                                                                "apis": count}
                                                               for (decision, spdx, basis), count in
                                                               sorted(licences.items(), key=lambda item: -item[1])]},
                  reader, facts, complete=False, scope=line.STATE_SCOPE)


def openapi_discovery(args) -> dict:
    from supply_lines import google_discovery as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=64 * 1024 * 1024)
    built, refusals, facts, summary = line.generate(
        reader, code_revision=revision, licence_text=LICENCE_FILE.read_bytes(), generated_on=now_utc()[:10],
        staging=run_folder / "staging", only=args.api, maximum_apis=args.maximum_apis)
    # A run that read every chosen document may withdraw what it no longer supplies; one that could not read a
    # document keeps that document's earlier packages.
    unread = any(row["reason"] == "specification_unreadable" for row in refusals)
    return finish(args, records.OPENAPI_OPERATIONS, built, refusals, {"discovery": summary}, reader, facts,
                  complete=not args.api and not args.maximum_apis and not unread, scope=line.STATE_SCOPE)


def programs(args) -> dict:
    from supply_lines import program_installs as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    rows = line.read_sources()
    catalogue, skipped = None, {}
    if args.catalogue:
        catalogue = reader.get(line.CATALOGUE_URL)
        if catalogue.status != 200:
            raise SystemExit("the Homebrew formula catalogue did not answer")
        extra, skipped = line.catalogue_rows(json.loads(catalogue.body), {row["formula"] for row in rows})
        rows = rows + extra
    if args.formula:
        rows = [row for row in rows if row["formula"] in args.formula]
    if args.maximum_programs:
        rows = rows[:args.maximum_programs]
    repositories = sorted({row["repository"] for row in rows if row["repository"]} | {line.HOMEBREW_CORE})
    facts_by_repository = reader.repository_facts(repositories)
    built, refusals, facts, summary = line.generate(reader, rows, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging",
                                                    repository_facts=facts_by_repository, catalogue=catalogue)
    return finish(args, records.PROGRAM_INSTALLS, built, refusals,
                  {"smoke_tests": summary, "programs_considered": len(rows), "catalogue_skipped": skipped},
                  reader, facts, complete=not args.formula and not args.maximum_programs and bool(args.catalogue))


def data_tables(args) -> dict:
    from supply_lines import data_tables as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    rows = line.read_sources()
    if args.table:
        rows = [row for row in rows if row["table_id"] in args.table]
    facts_by_repository = reader.repository_facts(sorted({row["repository"] for row in rows}))
    built, refusals, facts = line.generate(reader, rows, code_revision=revision,
                                           licence_text=LICENCE_FILE.read_bytes(), generated_on=now_utc()[:10],
                                           staging=run_folder / "staging", repository_facts=facts_by_repository)
    return finish(args, records.DATA_TABLES, built, refusals, {"tables_declared": len(rows)}, reader, facts,
                  complete=not args.table)


def publisher_tables(args) -> dict:
    from supply_lines import publisher_tables as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    sources = line.read_sources()
    # GitHub is not read: every fact is the publisher's own address or the licence steward's.
    reader = FactReader(run_folder, line.hosts(sources, args.collection), maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=64 * 1024 * 1024, github=False)
    built, refusals, facts, summary = line.generate(
        reader, args.collection, sources=sources, code_revision=revision, licence_text=LICENCE_FILE.read_bytes(),
        generated_on=now_utc()[:10], staging=run_folder / "staging", only=tuple(args.series or ()),
        maximum=args.maximum_series)
    proposal = line.sdg_map(built, now_utc()[:10])
    (run_folder / "sdg-goals.json").write_text(json.dumps(proposal, indent=1) + "\n", encoding="utf-8")
    # A run limited to some series, stopped early or unable to read one series is not complete: it withdraws
    # nothing it did not read again.
    unread = any(row["reason"] in line.UNREAD_REASONS for row in refusals) or bool(summary.get("stopped"))
    return finish(args, records.PUBLISHER_TABLES, built, refusals,
                  {"collection": args.collection, "summary": summary, "payload_files": line.payload_counts(built),
                   "sdg_goals": {key: proposal[key] for key in ("sources_per_goal", "without_goal")}},
                  reader, facts, complete=not args.series and not args.maximum_series and not unread,
                  scope=args.collection)


def functions(args) -> dict:
    from supply_lines import function_extracts as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    sources = line.read_sources()
    if args.source:
        sources = [row for row in sources if row["source_id"] in args.source]
    facts_by_repository = reader.repository_facts(sorted({row["repository"] for row in sources}))
    built, refusals, facts, summary = line.generate(reader, sources, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging",
                                                    repository_facts=facts_by_repository)
    return finish(args, records.FUNCTION_EXTRACTS, built, refusals, {"libraries": summary}, reader, facts,
                  complete=not args.source)


def schemas(args) -> dict:
    from supply_lines import json_schemas as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    built, refusals, facts, summary = line.generate(reader, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging",
                                                    only=args.schema, maximum_schemas=args.maximum_schemas)
    unread = any(row["reason"] == "schema_unreadable" for row in refusals)
    return finish(args, records.JSON_SCHEMAS, built, refusals, {"schemas": summary}, reader, facts,
                  complete=not args.schema and not args.maximum_schemas and not unread)


def curated_schemas(args) -> dict:
    from supply_lines import json_schemas as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    sources = line.read_sources()
    if args.source:
        sources = [row for row in sources if row["source_id"] in args.source or row["repository"] in args.source]
    built, refusals, facts, summary = line.generate_curated(reader, sources, code_revision=revision,
                                                            licence_text=LICENCE_FILE.read_bytes(),
                                                            generated_on=now_utc()[:10],
                                                            staging=run_folder / "staging")
    unread = any(row["reason"] in ("source_unreadable", "schema_unreadable") for row in refusals)
    return finish(args, records.JSON_SCHEMAS, built, refusals, {"sources": summary}, reader, facts,
                  complete=not args.source and not unread, scope=line.CURATED_STATE_SCOPE)


def api_schemas(args) -> dict:
    from supply_lines import api_schemas as line
    from supply_lines import openapi_operations
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, openapi_operations.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=128 * 1024 * 1024)
    sources = openapi_operations.read_sources()
    if args.source:
        sources = [row for row in sources if row["source_id"] in args.source]
    built, refusals, facts, summary = line.generate(reader, sources, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging")
    unread = any(row["reason"] == "source_unreadable" for row in refusals)
    return finish(args, records.JSON_SCHEMAS, built, refusals, {"specifications": summary}, reader, facts,
                  complete=not args.source and not unread, scope=line.STATE_SCOPE)


def manim_scenes(args) -> dict:
    from supply_lines import manim_scenes as line
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    # The scenes render in the interpreter that has Manim (a private environment, never the repository's); the
    # test runs in bubblewrap with the network closed when the machine has it.
    try:
        namespace = line.read_namespace(args.manim_python)
    except (RuntimeError, OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"the --manim-python interpreter cannot render: {str(error)[:300]}")
    cache = run_folder / "render-cache"
    cache.mkdir(exist_ok=True)
    runtime = line.Runtime(args.manim_python, namespace, cache, bwrap=None if args.no_bubblewrap else
                           shutil.which("bwrap"), seconds=args.scene_seconds or line.TEST_SECONDS)
    reader = FactReader(run_folder, line.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds)
    facts_by_repository = reader.repository_facts([line.REPOSITORY]) if args.stars else {}
    built, refusals, facts, summary = line.generate(
        reader, runtime=runtime, code_revision=revision, licence_text=LICENCE_FILE.read_bytes(),
        generated_on=now_utc()[:10], staging=run_folder / "staging", repository_facts=facts_by_repository,
        only=args.scene, maximum=args.maximum_scenes, workers=args.workers, tag=args.tag or line.RELEASE_TAG)
    (run_folder / "scenes.json").write_text(json.dumps(summary, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    unread = any(row["reason"] == "source_unreadable" for row in refusals)
    return finish(args, records.MANIM_SCENES, built, refusals,
                  {"release": {key: summary.get(key) for key in ("repository", "tag", "commit", "licence")},
                   "renderer": summary["renderer"], "sandbox": summary["sandbox"],
                   "directives": summary.get("directives")},
                  reader, facts, complete=not args.scene and not args.maximum_scenes and not unread)


def api_tool_servers(args) -> dict:
    from supply_lines import api_tool_servers as line
    from supply_lines import openapi_operations
    run_folder = _outside(args.run_folder)
    run_folder.mkdir(parents=True, exist_ok=True)
    revision = code_revision(args.authorize_store_writes)
    reader = FactReader(run_folder, openapi_operations.HOSTS, maximum_requests=args.maximum_requests,
                        pause_seconds=args.pause_seconds, maximum_bytes=128 * 1024 * 1024)
    sources = openapi_operations.read_sources()
    if args.source:
        sources = [row for row in sources if row["source_id"] in args.source]
    facts_by_repository = reader.repository_facts(sorted({row["repository"] for row in sources})) if args.stars else {}
    built, refusals, facts, summary = line.generate(reader, sources, code_revision=revision,
                                                    licence_text=LICENCE_FILE.read_bytes(),
                                                    generated_on=now_utc()[:10], staging=run_folder / "staging",
                                                    repository_facts=facts_by_repository)
    # A run that could not read a chosen file keeps that file's earlier server instead of withdrawing it.
    unread = any(row["reason"] == "specification_unreadable" for row in refusals)
    return finish(args, records.API_TOOL_SERVERS, built, refusals,
                  {"specifications": summary, "tools": sum(row.get("tools", 0) for row in summary)}, reader, facts,
                  complete=not args.source and not unread)


def report(args) -> dict:
    from licensed_import.composition import library_counts, load_targets
    from licensed_import.storage import ImportStore
    from supply_lines.report import build_report
    targets = load_targets()
    library = library_counts(args.library_bundle, targets)
    library["bundle"] = Path(args.library_bundle).name
    store = ImportStore(Path(args.store_root), writes_authorized=False)
    try:
        result = build_report(store, targets, library, review_batches=Path(args.review_batches),
                              daily=Path(args.daily), slot=args.slot, ceiling=args.per_repository,
                              served_bundle=Path(args.library_bundle), admission_folders=args.admission_folder or ())
    finally:
        store.close()
    result["written_at"] = now_utc()
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(json.dumps(result, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({key: result[key] for key in ("library", "approval")}, indent=1, default=str)[:3000])
    return result


def parser() -> argparse.ArgumentParser:
    main = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = main.add_subparsers(dest="command", required=True)

    def common(sub):
        sub.add_argument("--run-folder", required=True, help="outside the repository, for example "
                         "/home/username/baltor-library/supply/<line>/<date>")
        sub.add_argument("--store-root", default="/home/username/baltor-library/import-store")
        sub.add_argument("--authorize-network-reads", action="store_true", required=True)
        sub.add_argument("--authorize-store-writes", action="store_true")
        sub.add_argument("--materialize", action="store_true", help="also write every package under the run folder")
        sub.add_argument("--maximum-requests", type=int, default=6000)
        sub.add_argument("--pause-seconds", type=float, default=0.25, help="the least pause between two requests")
        sub.add_argument("--minimum-free-gigabytes", type=float, default=MINIMUM_FREE_GIGABYTES,
                         help="store nothing when the store's disk has less free space than this")

    one = commands.add_parser("mcp-registry")
    common(one)
    one.add_argument("--maximum-entries", type=int, default=100_000)
    one.add_argument("--maximum-lookups", type=int, default=4000, help="upstream licence reads at most")
    one.add_argument("--stars", action="store_true", help="read each upstream repository's stars (GraphQL)")
    two = commands.add_parser("openapi")
    common(two)
    two.add_argument("--source", action="append", help="only these source identities of openapi_sources.json")
    two.add_argument("--stars", action="store_true", help="read each repository's stars (GraphQL)")
    directory = commands.add_parser("openapi-directory")
    common(directory)
    directory.add_argument("--api", action="append", help="only these APIs (name or provider) of the directory")
    directory.add_argument("--maximum-apis", type=int, default=0, help="at most this many APIs, in name order")
    directory.add_argument("--exclude-api", action="append", help="leave out these APIs (name or provider), so a "
                           "large directory runs in slices whose packages are stored slice by slice")
    discovery = commands.add_parser("openapi-discovery")
    common(discovery)
    discovery.add_argument("--api", action="append", help="only these API names (drive, compute, ...)")
    discovery.add_argument("--maximum-apis", type=int, default=0, help="at most this many APIs, in path order")
    three = commands.add_parser("programs")
    common(three)
    three.add_argument("--formula", action="append", help="only these formulae")
    three.add_argument("--catalogue", action="store_true",
                       help="also every formula of Homebrew's catalogue with an allowlisted licence and executables")
    three.add_argument("--maximum-programs", type=int, default=0)
    functions_command = commands.add_parser("functions")
    common(functions_command)
    functions_command.add_argument("--source", action="append", help="only these source identities of "
                                   "function_sources.json")
    schemas_command = commands.add_parser("schemas")
    common(schemas_command)
    schemas_command.add_argument("--schema", action="append", help="only these SchemaStore schema names")
    schemas_command.add_argument("--maximum-schemas", type=int, default=0)
    curated_schemas_command = commands.add_parser("curated-schemas")
    common(curated_schemas_command)
    curated_schemas_command.add_argument("--source", action="append", help="only these source identities (or "
                                         "repositories) of json_schema_sources.json")
    api_schemas_command = commands.add_parser("api-schemas")
    common(api_schemas_command)
    api_schemas_command.add_argument("--source", action="append", help="only these source identities of "
                                     "openapi_sources.json")
    manim_command = commands.add_parser("manim-scenes")
    common(manim_command)
    manim_command.add_argument("--manim-python", required=True,
                               help="an interpreter that imports Manim Community (a private environment)")
    manim_command.add_argument("--tag", help="another release tag of ManimCommunity/manim than the pinned one")
    manim_command.add_argument("--scene", action="append", help="only these scene names")
    manim_command.add_argument("--maximum-scenes", type=int, default=0)
    manim_command.add_argument("--workers", type=int, default=3, help="scene tests run at once")
    manim_command.add_argument("--scene-seconds", type=float, help="the most seconds one test runs")
    manim_command.add_argument("--no-bubblewrap", action="store_true",
                               help="run the tests without bubblewrap (the network is still closed in Python)")
    manim_command.add_argument("--stars", action="store_true", help="read the repository's stars (GraphQL)")
    tool_servers_command = commands.add_parser("api-tool-servers")
    common(tool_servers_command)
    tool_servers_command.add_argument("--source", action="append", help="only these source identities of "
                                      "openapi_sources.json")
    tool_servers_command.add_argument("--stars", action="store_true", help="read each repository's stars (GraphQL)")
    four = commands.add_parser("data-tables")
    common(four)
    four.add_argument("--table", action="append", help="only these table identities of data_table_sources.json")
    publisher = commands.add_parser("publisher-tables")
    common(publisher)
    from supply_lines.publisher_tables import SOURCES_FILE
    publisher.add_argument("--collection", required=True,
                           choices=sorted(json.loads(SOURCES_FILE.read_text(encoding="utf-8"))["collections"]),
                           help="a collection of publisher_table_sources.json")
    publisher.add_argument("--series", action="append", help="only these series codes (World Development "
                           "Indicators) or table identities (O*NET) of the collection")
    publisher.add_argument("--maximum-series", type=int, default=0, help="at most this many series, catalogue order")
    # The World Bank and the O*NET Resource Center publish no numeric request rate: one request a second, serial.
    publisher.set_defaults(pause_seconds=1.0)
    five = commands.add_parser("report")
    five.add_argument("--store-root", default="/home/username/baltor-library/import-store")
    five.add_argument("--library-bundle", required=True, help="the served release bundle folder; a candidate whose "
                      "package it serves is not counted as supply")
    five.add_argument("--admission-folder", action="append",
                      help="an admission folder (its reviews.json) whose approved packages are not counted as supply")
    five.add_argument("--review-batches", default="/home/username/baltor-library/review-batches")
    five.add_argument("--daily", default="/home/username/baltor-library/daily")
    five.add_argument("--slot", type=int, default=2000)
    five.add_argument("--per-repository", type=int, default=15, help="the daily export's ceiling per repository")
    five.add_argument("--output", required=True, help="the report file (counts only, no third-party text)")
    return main


def main(argv=None) -> int:
    args = parser().parse_args(argv)
    # The run record states when the run began and how long it took, so each line's yield per hour is measured.
    args.started_at, args.started_clock = now_utc(), time.monotonic()
    {"mcp-registry": mcp_registry, "openapi": openapi, "openapi-directory": openapi_directory,
     "openapi-discovery": openapi_discovery, "programs": programs, "data-tables": data_tables,
     "publisher-tables": publisher_tables,
     "functions": functions, "schemas": schemas, "curated-schemas": curated_schemas, "api-schemas": api_schemas,
     "manim-scenes": manim_scenes, "api-tool-servers": api_tool_servers, "report": report}[args.command](args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
