"""Build the records index: every dated record under docs, grouped by folder and subject.

A dated record is a file whose name carries a date, dashed (2026-09-18) or
compact (20260918). The index lists every such record under its folder and
its subject stem (the name with the date removed), versions in date order
with the newest first, so a reader sees all versions of one subject in one
place without any file being moved. Undated files are living documents and
are not listed.

Usage:

    python tools/build_records_index.py            # write docs/RECORDS-INDEX.md
    python tools/build_records_index.py --check    # exit 1 when the committed index is stale

The tool reads only file names. It never reads or changes record bodies.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

INDEX_NAME = "RECORDS-INDEX.md"
DATED_NAME = re.compile(
    r"^(?P<stem>.*?)[-_]?(?P<date>\d{4}-\d{2}-\d{2}|\d{8})(?P<rest>(?:[-_.][^/]*?)?)$")
SKIP_DIRECTORIES = ("node_modules", ".cache", "__pycache__")


def normalize_date(text: str) -> str:
    """A dashed ISO date from a dashed or compact date text."""
    if len(text) == 8 and text.isdigit():
        return f"{text[:4]}-{text[4:6]}-{text[6:]}"
    return text


def classify(name: str) -> "tuple[str, str] | None":
    """The (subject stem, ISO date) of a dated file or folder name, else None."""
    base, extension = os.path.splitext(name)
    if base.endswith(".schema"):
        return None
    match = DATED_NAME.match(base if extension else name)
    if match is None:
        return None
    stem = (match.group("stem") + match.group("rest")).strip("-_. ")
    if not stem:
        return None
    return stem, normalize_date(match.group("date"))


def dated_records(docs: Path) -> dict:
    """{folder: {stem: [(date, relative path)]}} for every dated record under docs."""
    groups: dict = {}
    for root, directories, files in os.walk(docs):
        directories[:] = sorted(item for item in directories if item not in SKIP_DIRECTORIES)
        rel_root = Path(root).relative_to(docs)
        folder = rel_root.parts[0] if rel_root.parts else "."
        entries = list(files)
        # A dated folder counts as one record; its contents are not walked as records.
        for directory in list(directories):
            if classify(directory) is not None:
                entries.append(directory + "/")
                directories.remove(directory)
        for name in sorted(entries):
            if name == INDEX_NAME:
                continue
            item = classify(name.rstrip("/"))
            if item is None:
                continue
            stem, date = item
            path = f"{rel_root.as_posix()}/{name}" if rel_root.parts else name
            groups.setdefault(folder, {}).setdefault(stem, []).append((date, path))
    return groups


def render_version(date: str, path: str) -> str:
    """One version line; a dated folder is named, not linked, so link checks stay exact."""
    if path.endswith("/"):
        return f"  - {date}: `{path}`"
    return f"  - {date}: [{path}]({path})"


def render(groups: dict) -> str:
    lines = ["# Records index", "",
             "Every dated record under `docs`, grouped by folder and subject, with the versions",
             "in date order and the newest first. A dated record is a point-in-time statement;",
             "the newest version of a subject supersedes the older ones. Undated files are living",
             "documents and are not listed. Generated by `python tools/build_records_index.py`;",
             "`--check` fails when this file is stale.", ""]
    total = sum(len(versions) for stems in groups.values() for versions in stems.values())
    subjects = sum(len(stems) for stems in groups.values())
    lines.append(f"Records: {total}. Subjects: {subjects}. Folders: {len(groups)}.")
    lines.append("")
    for folder in sorted(groups):
        lines.append(f"## {folder}")
        lines.append("")
        for stem in sorted(groups[folder]):
            versions = sorted(groups[folder][stem], key=lambda item: (item[0], item[1]), reverse=True)
            label = f"{stem} ({len(versions)} versions)" if len(versions) > 1 else stem
            lines.append(f"- {label}")
            for date, path in versions:
                lines.append(render_version(date, path))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build(docs: Path) -> str:
    return render(dated_records(docs))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--docs", default=str(Path(__file__).resolve().parents[1] / "docs"))
    parser.add_argument("--output", default="")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the committed index differs from the generated one")
    args = parser.parse_args(argv)
    docs = Path(args.docs)
    output = Path(args.output) if args.output else docs / INDEX_NAME
    text = build(docs)
    if args.check:
        current = output.read_text("utf-8") if output.is_file() else ""
        if current != text:
            sys.stderr.write(f"{output} is stale; run python tools/build_records_index.py\n")
            return 1
        print(f"{output} is current")
        return 0
    output.write_text(text, "utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
