"""Tests for tools/build_records_index.py.

The fixtures are temporary documentation trees; one test also runs the
check against the real docs tree so a dated record added without
regenerating the committed index fails here, the same way the generated
architecture map is gated.
"""
from __future__ import annotations

import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import build_records_index as tool  # noqa: E402


class ClassifyTests(unittest.TestCase):
    def test_dashed_and_compact_dates_are_recognized(self):
        self.assertEqual(tool.classify("FEATURE-PLAN-2026-09-18.md"), ("FEATURE-PLAN", "2026-09-18"))
        self.assertEqual(tool.classify("adaptive-completion-20260906.json"),
                         ("adaptive-completion", "2026-09-06"))
        self.assertEqual(tool.classify("brain-integration-20260905"), ("brain-integration", "2026-09-05"))

    def test_undated_and_schema_files_are_not_records(self):
        self.assertIsNone(tool.classify("getting-started.md"))
        self.assertIsNone(tool.classify("benchmark-registry.schema.json"))
        self.assertIsNone(tool.classify("2026-09-18.md"))


class IndexTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.docs = Path(self.directory.name)
        (self.docs / "research").mkdir()
        (self.docs / "research" / "LANDSCAPE-2026-09-01.md").write_text("a", "utf-8")
        (self.docs / "research" / "LANDSCAPE-2026-09-18.md").write_text("b", "utf-8")
        (self.docs / "research" / "README.md").write_text("Kind: research", "utf-8")
        (self.docs / "evidence" / "run-20260905").mkdir(parents=True)
        (self.docs / "evidence" / "run-20260905" / "inner-2026-01-01.json").write_text("{}", "utf-8")
        (self.docs / "guides").mkdir()
        (self.docs / "guides" / "settings.md").write_text("undated", "utf-8")

    def tearDown(self):
        self.directory.cleanup()

    def test_versions_of_one_subject_are_grouped_newest_first(self):
        text = tool.build(self.docs)
        self.assertIn("- LANDSCAPE (2 versions)", text)
        newest = text.index("2026-09-18: [research/LANDSCAPE-2026-09-18.md]")
        oldest = text.index("2026-09-01: [research/LANDSCAPE-2026-09-01.md]")
        self.assertLess(newest, oldest)

    def test_a_dated_folder_is_one_record_and_its_contents_are_not_walked(self):
        text = tool.build(self.docs)
        self.assertIn("2026-09-05: `evidence/run-20260905/`", text)
        self.assertNotIn("inner-2026-01-01", text)

    def test_undated_files_and_the_index_itself_are_not_listed(self):
        (self.docs / tool.INDEX_NAME).write_text("old", "utf-8")
        text = tool.build(self.docs)
        self.assertNotIn("settings.md", text)
        self.assertNotIn(tool.INDEX_NAME, text.split("Generated by")[0])
        self.assertIn("Records: 3. Subjects: 2. Folders: 2.", text)

    def test_check_reports_a_stale_index_and_write_repairs_it(self):
        self.assertEqual(tool.main(["--docs", str(self.docs), "--check"]), 1)
        self.assertEqual(tool.main(["--docs", str(self.docs)]), 0)
        self.assertEqual(tool.main(["--docs", str(self.docs), "--check"]), 0)
        (self.docs / "research" / "LANDSCAPE-2026-09-19.md").write_text("c", "utf-8")
        self.assertEqual(tool.main(["--docs", str(self.docs), "--check"]), 1)


class CommittedIndexTests(unittest.TestCase):
    def test_the_committed_index_is_current(self):
        docs = Path(__file__).resolve().parents[1] / "docs"
        self.assertEqual(tool.main(["--docs", str(docs), "--check"]), 0,
                         "run python tools/build_records_index.py and commit docs/RECORDS-INDEX.md")


if __name__ == "__main__":
    unittest.main()
